### ISSUE TITLE
ffprobe and avprobe not found in $PATH after 0.3.31 update

### ISSUE THREAD

**Issue by bleugray** [xbapps/xbvr#1039]
running xbvr on unraid in a docker with the 0.3.31 update

ffprobe and avprobe not found in $PATH

i assume this is not an xbvr issue but missing a dependency?

**Comment by org0ne** [comment]
same issue here

**Comment by theRealKLH** [comment]
That is not an issue, it is just a statement saying "these apps are not in the PATH".
