### ISSUE TITLE
Deleted files listed not removed from "available right now"

### ISSUE THREAD

**Issue by flonglong** [xbapps/xbvr#1104]
Delete files on my hard drive are listed as scenes in "Available right now". That's the case also after rescans and restart of XBVR. I'm sure they were removed automatically before. Is this a bug, or is there some button I need to press to clean the database? Thanks!

**Comment by theRealKLH** [comment]
@flonglong still the same after latest release?

**Comment by flonglong** [comment]
@theRealKLH yes, the issue persists also in 0.3.33. I also rescanned after migrating to 0.3.33.

**Comment by theRealKLH** [comment]
can you try Options/Cache/Refresh Scenes?

**Comment by flonglong** [comment]
That worked, thanks!

**Comment by flonglong** [comment]
Got it, thanks. And thank you for your detailed response, @toshski :raised_hands: I'll close this issue. Keep up the good work :muscle:
