### ISSUE TITLE
Suggestions : Language switching for JAV scrapers

### ISSUE THREAD

**Issue by Yuubagi** [xbapps/xbvr#1132]
I am using xbvr in Japan. How do I switch the language of JAV scrapers.
For example, I would like to use "https://www.javbus.com/ja/" instead of "https://www.javbus.com/en/".

**Comment by vt-idiot** [comment]
The way it's currently set up, it's hardcoded. You'd have to change a few lines of code, [example for javbus](https://github.com/xbapps/xbvr/compare/master...vt-idiot:xbvr:patch-3)

**Comment by Yuubagi** [comment]
Thanks for your reply. I have no knowledge about programming so it is difficult for me to build it by myself. I would appreciate it if you could build it for me if possible.

**Comment by Yuubagi** [comment]
Thanks for your reply.
I built it myself and it stopped in the state shown in the image. Do you know the solution?
I am sorry to say that I have very little knowledge about programming.
![WS000392](https://user-images.githubusercontent.com/83891835/224485277-6a4ae05d-f855-48e5-a88b-312a51ec1023.JPG)

**Comment by Yuubagi** [comment]
Thanks for the reply. I rewrote the file as you mentioned but it did not work. Do you know why?
![WS000393](https://user-images.githubusercontent.com/83891835/224572019-383237e0-b98f-4a23-8943-3024e199f267.JPG)

**Comment by vt-idiot** [comment]
Because you're using the wrong URL? lol

`https://www.javbus.com/ja/3DSVR-0774`

so search for `3DSVR-0774` if you're using javbus

**Comment by Yuubagi** [comment]
Seriously! I didn't notice that at all. 
But to actually make it work correctly, I had to change 
"if label == `Studio:` {" to Japanese like "if label == `メーカー:` {".
Thanks for all your advice.

**Comment by Yuubagi** [comment]
自分はこのようにすればうまくいきました。もし同じ問題をお持ちの方がいたら参考にしてください。
https://github.com/Yuubagi/xbvrJP/blob/c58753ab6fd315d57580f2015be97792a8c5e704/pkg/scrape/javbus.go
