### ISSUE TITLE
SexbabesVR webpage redesign

### ISSUE THREAD

**Issue by Samsonite121** [xbapps/xbvr#1274]
After the recent newly published SexbabesVR website the scraper is not working anymore. Even thumbnails and scene pictures for already scraped and matched scenes are not available anymore.

**Comment by theRealKLH** [comment]
It's being "looked at". They have made the site less scrapable. ATM, a new scraper would not be 100% due to missing info and multiple filenaming formats.

**Comment by vt-idiot** [comment]
_significantly_ less scrapable. they seem to be using some backend similar to what VRPFilms uses. or they have a likeminded (read: no minded) webdev. their new scene URLs don't have any unique IDs in them, so scenes with the same name - and SexBabes has _several_ - clobber each other entirely

**Comment by theRealKLH** [comment]
we've got the scene IDs, @toshski PR #1280 is jiggering the release date issue. Now it's down to the duration missing and the mix of filename formats (I believe there are at least 3).

**Comment by crwxaj** [comment]
fixed in 0.4.9
