### ISSUE TITLE
Feature request: filter scenes with no script associated

### ISSUE THREAD

**Issue by CyberDrenDor** [xbapps/xbvr#1275]
We have a wonderful button to filter out scenes that don't have a script, which is great, but I have often found myself wanting the reverse as well. When looking for scenes that don't yet have a script I have to scroll past all my scenes that do have a script and the ones that don't get lost in the weeds. Having a button to just show me all the scenes that don't have a script would be super helpful, at least to me, I'm sure others would find it helpful as well.

**Comment by theRealKLH** [comment]
use the attributes option.. type "scr" and select the `is Scripted` attribute. Then click it twice to get the "not" (red) value.

![image](https://github.com/xbapps/xbvr/assets/65736720/5a50537e-eb9d-4049-8149-45b6be2ac9ad)

**Comment by crwxaj** [comment]
This is the way
