### ISSUE TITLE
Search index not rebuilding properly

### ISSUE THREAD

**Issue by cwkowalski** [xbapps/xbvr#1314]
[xbvr.log](https://github.com/xbapps/xbvr/files/11991707/xbvr.log)

Logs attached (not sure how to enable trace level logging). Running latest image in Docker. Fresh install, scraped all sites, then when I got to matching noticed only ~1/3rd of scenes from scraped sites appeared in the "Files" tab. However, I can find those same scenes via "Scenes" tab... there are no appropriate results in "Files" when searching with broad criteria or by the ID listed in "Scenes". 

What I've tried to resolve the issue:
Restarted xbvr docker container.
Rescanned storage folders.
Rescraped associated sites.
Cleared search index in Options->Cache. This did not rebuild the search index, even when restarting the container or clicking 'Refresh Scenes' in Options->Cache, and now no scenes at all appear in "Files" tab. Search index remains 0 bytes hours later, after restart, rescan, rescrape, refresh. 

Based on logs it looks like "Refresh Scenes" is not the same function as rebuilding the search index. There doesn't appear to be a way to manually trigger search index rebuild. Helpful discord people reported it should rebuild automatically after clearing the cache, but it does not.

**Comment by toshski** [comment]
You can manually trigger a scan with the task/index API, e.g.
http://[localhost:9999/api/task/index](http://localhost:9999/api/task/index)

Try the API manually, if still stuck I've also done a mod to provide a little more detail and control - the Rescan button just calls the task/index API.  If you want I should be able to publish a docker image with 0.4.9 + the mod.

![image](https://github.com/xbapps/xbvr/assets/104477758/84aed952-657e-4e52-984e-777cd9f51766)

![image](https://github.com/xbapps/xbvr/assets/104477758/430c9f5b-46f7-48d6-95b7-5e9791c5cb80)

**Comment by cwkowalski** [comment]
The API did trigger the index scan, excellent tip. I waited a while after it finished indexing >20,000 titles, and the search index cache was just 65.6kb. For like an hour. But then, it updated to >90mb... now it works. Thanks!
