### ISSUE TITLE
CZECHVRNETWORK scraper does not scrape scenes released in 2023

### ISSUE THREAD

**Issue by rajatmodi62** [xbapps/xbvr#1340]
Hi, 
i was trying to scrape the czechvrnetwork scenes using xbvr. however, the latest xbvr  version (and the version before that)  does not scrape any scenes after dec 2022. 

could someone please look into it, 
thanks,

**Comment by theRealKLH** [comment]
things look fine to me. Only scenes not being scraped are the ones that have been removed from the site. As of 07/22/2023, a brand new db = 1272 scenes across all 4 sites.

**Comment by vileda12** [comment]
Same issue. Cannot scrape new czechvr scenes. Latest scene 6 of September. Total scenes 1275 in CZECHVRNETWORK
latest XBVR version 0.4.14

**Comment by vileda12** [comment]
Thanks for the speedy response. Seems to find new scenes now.

**Comment by theRealKLH** [comment]
@rajatmodi62 closing this issue since you have not responded. please open a new one if you are still having problems.
