### ISSUE TITLE
Search with contracted performer name 

### ISSUE THREAD

**Issue by dan9qt** [xbapps/xbvr#135]
I'm sure this will be an edge case so only worth doing if its a simple fix.

It would be great if the search would work on 'MyName' as well as 'My Name'

**Comment by cld9x** [comment]
This will get into next release, but please mind that you'll need to rebuild the search index (delete index folder first, then run indexing)

**Comment by dan9qt** [comment]
Brilliant, thanks for this. Will speed up matching for me a lot and hopefully others will find useful depending on their naming scheme
