### ISSUE TITLE
[feature request] Add option to generate preview images for unmatched scenes

### ISSUE THREAD

**Issue by letesch** [xbapps/xbvr#1359]
Hi,
first of all thanks for the great work :)
Currently only matched scenes get preview images.
I am using Heresphere on Quest 2 and without previews
or any screenshot whatsoever, the unmatched scenes are hard to identify.
I wanted to ask if it is possible to also include unmatched scenes in the preview generation process.
Maybe there is already some config file I am not aware of or maybe this can be added in a future release?
Thanks
letesch

**Comment by Ptorr** [comment]
its marked as completed but I'm not sure how to do this? Is there a way?
