### ISSUE TITLE
Add search's top hit to the file list with assign button

### ISSUE THREAD

**Issue by dan9qt** [xbapps/xbvr#136]
If the file list had the highest probability search added with an assign button, it would allow the user to quickly scroll down and hopefully add a good chunk of scenes in bulk just by recognising the title/cover art

**Comment by cld9x** [comment]
Making queries for all files while fetching the list would be too expensive. 

The only way it could happen is to make queries while scanning files.

**Comment by jrebey** [comment]
There has been some improvement to the scene matching dialog since this request was made. Matching a scene automatically progresses to the next one and there are prev/next buttons in the match UI now. Does this help?

**Comment by dan9qt** [comment]
Yeah, the search has improved so much over the last few betas that this probably wouldn't help that much anymore
