### ISSUE TITLE
XBVR doesn't work anymore with DeoVR 13.12.0

### ISSUE THREAD

**Issue by Samsonite121** [xbapps/xbvr#1379]
Yesterday my Pico 4 updated DeoVR to version 13.12.0. Aftewards XBVR isn't working anymore. I get the three spinning dots for a while, seems Deo is already loading the video lists but then instead of showing the video grid is switching to the web UI. There is a comment at the top of Deo that legacy websites should use the Deo Json scheme with a link to Deos app documentation. Seems Deo is checking s.th. in the video detail jsons.
I was on XBVR 0.4.11 and updated to XBVR 0.4.12, doesn't matter, same issue.
Unfortunately there is no Heresphere for Pico 4 to use instead and my XBVR library is useless.

**Comment by theRealKLH** [comment]
This is not an XBVR issue. DeoVR stopped supporting their legacy API a long time ago. It's "hit or miss". It will usually clear itself. What I would suggest is to navigate to some other site (Deo or SLR) and then manually type your local xbvr in (be sure to include the :9999). OR extreme would be to remove deovr and reinstall, but you may lose your cached info. I don't know if there is "any" difference between them (outside of forced upgrade), but maybe switching between "official" deo and "sidequest" deo...

**Comment by Samsonite121** [comment]
For all that are reading or following this isssue:
The problem is solved! Short notice: problem was not affected by a DeoVR update or XBVR update, only an unfortunate correlation. After a deep dive what changed I could identify the root cause:
I edited two scenes to change the cover image to a local storage path s.th like this: file:///D:\\Filme\\VR\Bilder\\...png This seemed to cause the DeoVR json parser to run into some exception!

But this also results in a [feature request] if any of the devs is reading this: I want to add some local files as images or covers that are stored on the machine running XBVR (Why add an additional webserver for that purpose!). Isn't it possible for the imageproxy to add local files to it's storage and present a URI for WebUI / DeoVR / Heresphere that are then accessible?
