### ISSUE TITLE
Add two site variants to the list of scrapers

### ISSUE THREAD

**Issue by undercutvibes** [xbapps/xbvr#139]
Hi, both these sites are variants of sites that already have scrapers. I hope that means adding them could be as simple as changing the domain name? The sites certainly look very similar in a browser, but I'm not sure what that means when it comes to scraping the HTML.

VirtualRealTrans is VirtualRealPorn
VRBTrans is VRBangers

Thanks again for all your hard work on this niche project. It's so much better than a flat list of filenames.

**Comment by vpfruitly** [comment]
I've moved these requests to issue #142 so we can probably close this one.
