### ISSUE TITLE
Support "Portable Mode"

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#140]
I'd like to see a portable mode where the db/data aren't automatically stashed in the user's profile directory, but kept with the executable itself. Something like:

To use "portable mode" you would pass an argument like `--portable` to the exe. The process would determine the full path it is running from, then check for the presence of an "xbvr" subfolder (or some other name?) and use that as the data dir.

This has two good benefits: portability and allowing users to store the (sometimes very large data folder) somewhere other than their main drive/partition.

**Comment by cld9x** [comment]
Good idea

**Comment by jrebey** [comment]
This can already be done through the use of go-appdata.

Simply set XDG_CONFIG_HOME environment variable on Linux or APPDATA on Windows to whatever path you want when running the binary.

On Linux:
XDG_CONFIG_HOME=/some/path xbvr

On Windows:
set APPDATA=c:\some\path && xbvr

Doing this will create an xbvr path if it doesn't exist, or use an existing one.

Let me know if it works on Windows!

**Comment by vpfruitly** [comment]
Yep, that absolutely works, but it's a bit much maybe to ask of end users. Something like a setting to pass in a path or check the current folder would be much simpler.

But I think it boils down to getting feedback on how wanted this feature is. Maybe it's just me, and I can certainly use this method, in which case it's not worth the development, testing, and added complexity.

**Comment by jrebey** [comment]
We've been steering folks towards Docker more and more. With docker, you can use volumes and store them wherever you want. I think using docker would be preferred over these types of features.

I'm not sure I see a major difference between `xbvr --appdata=/path/to/data` and the method I posted in regards to complexity for users aside from the differences in methods between platforms. But that's mostly a documentation issue.
