### ISSUE TITLE
VRspy scraper issue

### ISSUE THREAD

**Issue by logics102** [xbapps/xbvr#1403]
The VRSpy scraper seems to be scraping duplicates with different ID's and 404/blank covers. I assume it has something to do with website changes. It didn't do this before.

**Comment by qjao** [comment]
The video pages are not using the same format as its images url.

E.g. https://cdn.vrspy.com/videos/9/images/cover-details.jpg is the cover image of https://vrspy.com/videos/classical-trio
https://cdn.vrspy.com/videos/14/images/cover-details.jpg is the cover image of https://vrspy.com/videos/peeking-taboo-spend-a-penny

**Comment by theRealKLH** [comment]
There should be a PR waiting for merge to fix unless this is something different, the is already a PR (#1407) to fix..
