### ISSUE TITLE
xbvr fails with MariaDB 10.11

### ISSUE THREAD

**Issue by Mellified** [xbapps/xbvr#1420]
After a restore process that took a couple of days my xbvr no longer functions with MariaDB 10.11. Based on how long the restore was taking and what I'm seeing now there seems to be some kind of performance issue. The Options page works, but anything that queries the database for scenes seems to stall. I also cannot match files.

Everything was working OK with 10.3.

I have the connections set to 500 and the database reports a peak connection count under that.

It looks like this may be a known issue with certain database configurations. I'm guessing the description field is the culprit.

https://stackoverflow.com/questions/76375353/slow-queries-for-specific-table-after-upgrading-mariadb-10-3-to-10-11

**Comment by theRealKLH** [comment]
is this a new install of 10.11 and you restored into it? Or you upgraded to 10.11 and it stopped working (and then you tried a DB from 10.3)? I was about to upgrade my MariaDB docker... hmm... I'm actually hard coded to 10.5. must have been a reason..

**Comment by Mellified** [comment]
I tried upgrading my existing DB. I tried creating a new 10.11 DB and importing my xbvr JSON export. The problem was present in both cases.

There is also another user reporting the issue in the xbvr Discord.

**Comment by theRealKLH** [comment]
stop tryna be bleeding edge! grin

**Comment by Mellified** [comment]
I'm using the Synology MariaDB package. They jumped from 10.3 to 10.11 - I didn't want to get left behind on an old version.

In any case, this seems like a regression on MariaDB's part so the solution may be to note it and move on, assuming they'll fix it later.

**Comment by theRealKLH** [comment]
I did not have any issues going from 10.5 to 10.11. I did however add the `my.conf` settings (increase in a few memory settings) mentioned over in Discord. Don't know if they were actually needed since I didn't try before adding them.

**Comment by Mellified** [comment]
Adding the following lines to the `my.cnf` made MariaDB work as expected with 10.11.

```
[mysqld]
max_connections=500
innodb_buffer_pool_size=1024M
tmp_table_size=64M
max_heap_table_size=64M
query_cache_size=64M
```

**Comment by theRealKLH** [comment]
closing this as "Fixed via updating mysql configuration"
