### ISSUE TITLE
File Renaming and Organizing Features

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#143]
Something that would be nice (in the long term) is a way to manage your local files. Renaming them and maybe organizing by folder based on site.

Definitely some challenges to implementing this, but a way to "write back" all the organization work into the actual filesystem would make browsing folders directly nicer and would greatly speed up re-importing to xbvr (ie: if you lost the db or really screwed it up somehow and wanted to start over).

**Comment by cld9x** [comment]
Making it happen would mean lots of development to cater everyones needs, plus tons of testing to make sure everything is working as expected and no file would be lost in the process - all of which makes it serious endeavour.

Right now it's not something I'd consider as core feature, maybe once we proclaim 1.0 and start looking for new areas to explore.

**Comment by vpfruitly** [comment]
Yep, everything you said makes total sense. I have some experience writing a content organizer app and never lost a single file for any of my users. It takes some doing, but there are some easy guidelines to follow. Hopefully I'll be up to speed on the codebase by then and can pitch in.

**Comment by vpfruitly** [comment]
I'm closing this on account of being more familiar with the scrapers and how some sites don't even provide filenames. I don't think this is realistically achievable, unfortunately.
