### ISSUE TITLE
Tempor orci eu lobortis

### ISSUE THREAD

**Issue by t-900-a** [xbapps/xbvr#1442]
In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Luctus accumsan tortor posuere ac ut consequat semper viverra nam.

**Comment by theRealKLH** [comment]
You already have this functionality. Anything "downloaded/available now" is "matched".  In DeoVR anything "unmatched" is "unmatched". Not sure if HereSphere has the "unmatched" view. You can also get to all unmatched from the files tab. 

What are you trying to accomplish?

**Comment by t-900-a** [comment]
> What are you trying to accomplish?
Saved search that includes unmatched + random

**Comment by theRealKLH** [comment]
@t-900-a What was the purpose of you deleting what was posted here?????!!!!!????
