### ISSUE TITLE
h265 Support for Docker

### ISSUE THREAD

**Issue by jchilders99** [xbapps/xbvr#1464]
Running XVBR in Docker, h265 encoded videos are not supported.  They display in the Downloaded section, but not in the Available Now section in the web view, and when trying to play, the error "The media could not be loaded, either because the server or network failed or because the format is not supported." is presented.  I tested on a Mac, Windows, and Linux with Safari, Chrome and Firefox.  In DEOVR, the videos don't display at all.  Using DLNA to the storage (not through XVBR, I was unable to test XBVR DLNA), the videos play fine.

**Comment by theRealKLH** [comment]
not sure what we are talking about here. not displaying in "available now" means xbvr does not see the file (usually volume is missing). this has nothing to do with the format of the video. It just sounds like your volume mounts aren't correct in Docker.

**Comment by jchilders99** [comment]
> not sure what we are talking about here. not displaying in "available now" means xbvr does not see the file (usually volume is missing). this has nothing to do with the format of the video. It just sounds like your volume mounts aren't correct in Docker.

Wait I rebooted the container (again) and the issue is slightly different.  I now have h264 videos not displaying in Available Now that play fine when clicking the Play icon in the browser.  I have some of the h265 videos displaying as Available Now in the browser, but they fail to play with the same error.  These issues may not be related.  I'll check DEOVR to see if the h265 videos play correctly and if so, I'll ignore the browser issue and work on tracking down why some videos aren't available.

**Comment by jchilders99** [comment]
Tested and h265 videos play in DEOVR fine.  They won't play in any web browser I've tried so that might still be an issue, but it's not my use case so I'm going to close this one out.  I'll start on the discord for help with why available videos are showing as not available.
