### ISSUE TITLE
Play Trailers for Non-Downloaded Scenes

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#150]
Add in a link or embed with the scene's trailer,

**Comment by jrebey** [comment]
This is a pretty big change. Scrapers don’t currently scrape trailer urls. Until #156  is resolved, this won’t happen.

**Comment by Kaylakaze** [comment]
Well, #156 has been resolved for a few years now...

**Comment by theRealKLH** [comment]
added in release 0.3.30
