### ISSUE TITLE
Star Ratings (1 - 5) for Scenes

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#152]
Rather than just fav/not-fav, it would be nice to rate scenes on a scale.

**Comment by jrebey** [comment]
This feature partially exists but is broken. There are ratings in Scene Details but setting a rating doesn't save nor is there a way to sort/filter on ratings.

**Comment by cld9x** [comment]
Both saving and sorting by rating is in place already - the only thing missing is showing the rating in scene list

**Comment by jrebey** [comment]
The rating also doesn’t display in the scene details. It shows no rating, so if it’s saving then it’s not pulling those fields in the view. Seems easy enough to fix.
