### ISSUE TITLE
IP Whitelisting for DLNA Port

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#153]
Not everyone wants their library to show up on every media device on the network.

Possibly the best solution is to block everything by default, and then give an option in UI to whitelist selected addresses.

**Comment by jrebey** [comment]
I recently learned that anacrolinx/dms was forked into XBVR for DLNA support. This feature exists in the upstream version:

https://github.com/anacrolix/dms/blob/d7c7d67cc2aae6725a4e0faa6dba712489f8c07e/dlna/dms/dms.go#L532-L542

I need to get with @cld9x to see what modifications were made to the upstream version to evaluate whether we should backport this feature into our existing fork, rebase our fork and apply our modifications, or find a way to use the upstream dms package. A diff at this point would be too difficult for me to determine the modifications without context.

Using the upstream package would greatly simplify our codebase but might take some work to plug our content into it.

At the very least, maybe we can remove dms from the xbvr repo and move it into its own repo which might pave the way for merging any necessary changes back into upstream.
