### ISSUE TITLE
Display/Filter/Sort by Scene Metadata

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#154]
The ability to filter based on metadata (cast, tags, etc.) already exists which suggests that the data is already linked to a scene.

This request is the ability to see what metadata is available for a scene by clicking on the scene. I.e. if I click on a scene, I'd like to know who's in it and what tags are associated with it.

**Comment by jrebey** [comment]
I believe this is already done? Can we close this out?

**Comment by vpfruitly** [comment]
I agree.
