### ISSUE TITLE
VirtualPorn

### ISSUE THREAD

**Issue by guillorec** [xbapps/xbvr#1568]
First of all, THANK YOU.  This ability to organize my files has been a game changer.

However, virtualporn won't scrape any scenes.  All the other sites have worked for me. Even scraping single scene will say that it worked (Data - scraped 1 new scenes in 9s) But the scene isnt actually there.

**Comment by Samsonite121** [comment]
I've the same problem. The virtualporn scraper doesn't scrape scenes anymore after 11/21/2023. I think at that time they changed their site layout. If I'm not logged I also cannot download trailers anymore. There is only a streaming preview.
