### ISSUE TITLE
Better Logging and Communication

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#158]
When the user clicks a button in the Options menu, the UI should provide feedback about the success or failure of the action. This feedback could be provided by a notification on the bottom-right of the UI.

Examples:
- User clicks "Rescan"
    => Notification: "Scanning files ..."
- User clicks "Run Scraper"
    => Notification: "Running scraper ..."
- User clicks "Add new folder" without entering a path
    => Notification: "Error: please enter a path"

Right now, I need to watch the Docker logs to figure out what's actually happens. Adding feedback would be a huge quality of life improvement.

**Comment by jrebey** [comment]
This already partially exists. I’m planning on adding notifications in addition to the display on the bottom of the ui.

Also, in scrapers we added progress bars to each scraper so you can see which scraper have completed.

The logs that you see in docker are also available in the JavaScript console as well.
