### ISSUE TITLE
"database is locked" error on docker container

### ISSUE THREAD

**Issue by Raptor05** [xbapps/xbvr#1582]
Hey,

I'm running XBVR on docker container on my Synology NAS 918+. Because the scrappers where failing all the time at some point (I thought the task is to heavy for my NAS) I installed XBVR in parallel on my Desktop PC. I scrapped all sites I need and imported them to the other instance in the docker environment. So far so good. 

But now, every time a regular run is going on (e.g. scrapping actors from sites) at some point the process fail and the docker container restarts. 

In the log I can see the following errors:

> time="2024-01-11T19:19:41Z" level=info msg="visiting https://www.sexlikereal.com/pornstars/sandra-star"
> time="2024-01-11T19:19:43Z" level=info msg="visiting https://kinkvr.com/bdsm-performer/summer-hart"
> time="2024-01-11T19:19:44Z" level=info msg="visiting https://vrhush.com/models/shyla-ryder"
> time="2024-01-11T19:19:46Z" level=info msg="Lost 1981590822095174"
> time="2024-01-11T19:19:46Z" level=info msg="visiting https://www.sexlikereal.com/pornstars/lydia-black"
> time="2024-01-11T19:19:47Z" level=error msg="Error visiting https://vrhush.com/models/pepper-xo Get "https://vrhush.com/models/pepper-xo": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> time="2024-01-11T19:19:47Z" level=fatal msg="Failed to save All attempts fail:
> #1: UNIQUE constraint failed: actors.name
> #2: database is locked
> #3: UNIQUE constraint failed: actors.name
> #4: database is locked
> #5: database is locked
> #6: database is locked
> #7: database is locked
> #8: database is locked
> #9: UNIQUE constraint failed: actors.name
> #10: database is locked"
> 2024/01/11 19:19:58 ffprobe and avprobe not found in $PATH
> time="2024-01-11T19:19:59Z" level=info msg="Migration did run successfully"
> time="2024-01-11T19:20:00Z" level=info msg="Starting router "
> time="2024-01-11T19:20:00Z" level=info msg="Added realm: default"
> time="2024-01-11T19:20:00Z" level=info msg="XBVR 0.4.20 (build date 2024-01-02T15:25:22Z) starting..."
> 

XBVR Version: 0.4.20

Do you have any idea where that exception is coming from? I've had a look into the system monitor of my NAS in parallel. The CPU is never over 50% and RAM is available, too.

BR

**Comment by theRealKLH** [comment]
you need to switch from SQLITE to MariaDB... check out the WIKI page.

**Comment by Raptor05** [comment]
> you need to switch from SQLITE to MariaDB... check out the WIKI page.

What wiki do you mean? I can't find anything about MariaDB migration in the GitHub of XBVR.

**Comment by theRealKLH** [comment]
![image](https://github.com/xbapps/xbvr/assets/65736720/6a468eaa-be87-48cc-bbd1-6d047c29a5d0)

**Comment by Raptor05** [comment]
Ah thanks, found it. 

Do I need to install MariaDB via Synology and Docker? Or is it an alternative?

**Comment by theRealKLH** [comment]
however you want.. the Syno package, docker, another machine, etc...

**Comment by Raptor05** [comment]
unfortunately the export in the docker container is not working:

> stat /root/.config/xbvr/download/xbvr-content-bundle.json: no such file or directory
