### ISSUE TITLE
WankitNowVR/ZexyVR Cover double encoding URLs

### ISSUE THREAD

**Issue by Asparghus** [xbapps/xbvr#1603]
WankitNowVR/ZexyVR are using space on their cover images URLs.
E.g. https://j6k2m5e7.ssl.hwcdn.net/1931/o/artwork/8K-ARTWORK%20copy.jpg / https://j6k2m5e7.ssl.hwcdn.net/1924/o/artwork/8K-ARTWORK%20copy.jpg

They are being treated correctly when scrapped, but when it tries to display it, it reencodes the URL and changes the "%" to "%25" and it becomes url(&quot;/img/700,fit/https://j6k2m5e7.ssl.hwcdn.net/1924/o/artwork/8K-ARTWORK%2520copy.jpg?h=900&quot;);

Maybe #1602 is the same issue, but as the person didn't mention which Studio it was it will be hard to say.

**Comment by Asparghus** [comment]
I just found that VirtualRealPorn is also using "%C2%B4" on their cover URLs as well, like in virtualrealporn-278452 (https://virtualrealporn.com/wp-content/uploads/sites/5/2024/01/001_Portada_video_SM24H01-083-I%C2%B4m-Bored.jpg)

Same issue, just different Studio

**Comment by pops64** [comment]
That might be the underlying fault in#1602. Just weird as I copied and pasted the link in the scene detail assuming that was what it fetches when grabbing the image and my browser successfully displayed it. XBVR should still have a fall back in case the link goes dead/changes in the future
