### ISSUE TITLE
XBVR via dDocker/contrainer manager

### ISSUE THREAD

**Issue by Sunset-1982** [xbapps/xbvr#1612]
Hey!

My XBVR suddenly stopped working with the following errorlog on my Synology NAS. (via Docker/Container Manager)

![xbvr error](https://github.com/xbapps/xbvr/assets/155768642/b53b0cb4-c6a2-4778-bb84-d1d5ada4c31f)

Any idea what causes this issue?

**Comment by alexandre94533** [comment]
I have the same problem since updating the image.

**Comment by tstealth123** [comment]
Same issue on QNAP with QUTS hero h5.1.5.2647

**Comment by niconpl** [comment]
same problem , synology ds218+

**Comment by exceptship35** [comment]
same issue after updating

**Comment by Sunset-1982** [comment]
Did anyone find a solution?

**Comment by alexandre94533** [comment]
Several updates of the image over the last few days but the problem persists.

**Comment by tstealth123** [comment]
Still isn't working. Would love to get some attention on this from one of the devs. Please let us know if any more information would be helpful to get this resolved. Thanks!

**Comment by tstealth123** [comment]
@theRealKLH any help appreciated!

**Comment by niconpl** [comment]
guess we wait for a new update then.. hoping it will be fixed.

**Comment by alexandre94533** [comment]
It works again since the last update for me

**Comment by Sunset-1982** [comment]
yes, it is working again with the latest update!

**Comment by theRealKLH** [comment]
@alexandre94533 @Sunset-1982 @tstealth123 @niconpl @exceptship35 

The docker container that you are using is not supported here (in-fact it's ***NOT*** supported at all). I would advise you to install something like Portainer if you are unable to use built-in docker GUI (ex. Synology) to change docker registries (from docker hub to GHCR) and point to the OFFICIAL container `ghcr.io/xbapps/xbvr`.

Discord would be a more appropriate place to ask about this container. I stopped using it, and stopped "actively" keeping it updated a very long time ago.
