### ISSUE TITLE
Scraper Bug: Default Images for POVR & VRP Custom Sites

### ISSUE THREAD

**Issue by pops64** [xbapps/xbvr#1625]
When you leave the avatar blank with SLR custom sites it defaults to the SLR logo. I would love to see the same behavior for POVR & VRP. I love the new linked site feature but I prefer to use the agitator websites logo instead of the Studios logo. That way I can identify which link belongs to who. Another nice feature is use to this image like you do with stash to signify a stash link instead of the image provided by the user. Or some way to identify from XBVR instead of traversing the link which linked scene came from which source when viewing from XBVR.

This is the image used for the favicon for POVR https://images.povr.com/img/povr/android-icon-192x192.png
And the same for VRP https://vrporn.com/assets/favicon.png
Not sure if there is a better image for VRP

I have to say it again. Thanks for coding in linked scenes. This is a game changer for XBVR scrapers.

**Comment by theRealKLH** [comment]
You just happened onto a "bug" because you want to "be lazy" (grin). There is "missing" scraper code. submitting a PR. thanks for the eye.
