### ISSUE TITLE
Add ability to turn off file scanning by folder

### ISSUE THREAD

**Issue by SilentMonkee** [xbapps/xbvr#166]
Toggle for folder scanning similar to scraper on/off switch.

**Comment by dan9qt** [comment]
Yeah I think this would be a good option. I have scenes sorted by studio so it would be good to turn of ones that don't have scrapers

**Comment by jrebey** [comment]
What’s the benefit here? If there is no scraper then the file just doesn’t get matched. It’s not adding a significant amount of time to the scraping process.

**Comment by SilentMonkee** [comment]
I use Windows 10, when I scan my files, XBVR is popping up cmd wnd that's taking focus and making the machine unusable.  For most studio is fine it will just pop up a couple windows to scan, but for VRP it's poppuing up 263 times, and it takes minutes.  So the benefit here is if I didn't add a new file to my VRP folder I don't want to scan that folder to match, and have my machine not usable for 5 minutes.  Or if I only added 1 file to BaDonik folder, I just scan that folder.

**Comment by SilentMonkee** [comment]
@dan9qt  for your scenario, I add each studio folder individually, so that I won't scan the folders that don't have a scrapper and my match list won't have permanently unmatched file.

**Comment by cld9x** [comment]
If blocking cmd window is the problem, we should be looking at hiding it rather than adding option to disable folders!

**Comment by SilentMonkee** [comment]
Don't have to hide it, even if popping the windows up without taking focus would solve my issue.

**Comment by AKDub** [comment]
> @dan9qt for your scenario, I add each studio folder individually, so that I won't scan the folders that don't have a scrapper and my match list won't have permanently unmatched file.

Thats a good shout, not sure why I didn't manage to come up with that!

**Comment by vpfruitly** [comment]
I will raise a new issue with the cmd windows (I'm also on Windows and get that as well) and then it sounds like we can close this one out.

**Comment by cld9x** [comment]
That's now discussed in #168
