### ISSUE TITLE
My log file is multiple gigabyte

### ISSUE THREAD

**Issue by Exosq** [xbapps/xbvr#1666]
Hi, so i don’t know if it’s just me because i didn’t see anyone else post this issue when i searched.

Basically, yesterday i deleted a 492GB (yes GB) log file who was located in the config folder, i left xbvr open this night and now i deleted another log file that was 15GB.

Xbvr works fine for me and i have no issue other than this so i must be doing something wrong since nobody else has posted this.

I’m on Windows 11 with the latest xbvr build available. 

Thanks

**Comment by theRealKLH** [comment]
you need to look at what's in that log. you either have EVERY SITE + a shit ton of JAV in there or something is wrong. My log created in July is only 550MB.15gb in a single night is EXTREME.. 
![image](https://github.com/xbapps/xbvr/assets/65736720/06c2433d-77ae-4d6c-8b4c-e65e64e0f451)

How do your scheduled tasks look? Maybe you are doing too much? (I only scrape once a day and my file scans are manual). Maybe don't have repeating schedule like "every 15 minutes" (GRIN). keep it low like once or twice a day for things. I never understand for doing multiple scrapes/scans ALL DAY LONG... (not saying this is your problem, but it might be)

**Comment by theRealKLH** [comment]
EXCELLENT
