### ISSUE TITLE
Suppress File Scan Command Prompts on Windows

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#168]
On Windows OS, when scanning files, a new command prompt windows is created and then closes (over and over again, very fast) for each ffprobe process. (At least, I think it's ffprobe.) It makes your computer basically unusable because each new windows steals focus and so you can't do anything until they have stopped coming and going.

**Comment by jrebey** [comment]
I think it's ffmpeg/ffprobe as well. We should figure out how to not exec that in its own process.

**Comment by vpfruitly** [comment]
Well, I think I'm the only contributor using Windows, so maybe we can collab on Discord and test some things out. At the very least, if it's not possible to suppress the windows entirely, there should be a way to spawn the command prompt windows as minimized, so they don't steal focus.

**Comment by SpedNSFW** [comment]
I'm using Windows and not having this problem so I'm wondering if it's exclusive to cmd/Powershell as I'm using Bash.

**Comment by vpfruitly** [comment]
This was fixed a while back, yeah. Closing.
