### ISSUE TITLE
Browse/Filter/Sort by File Metadata (Not Scene)

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#169]
Hi, in closing #154 it made me think about how it would be useful to grab basic data on the files themselves. It looks like resolution and filesize is already captured, but framerate and bitrate (others?) would also be good.

At least once I have used those 3 values to determine which files to cull from my collection, so it may be of use to others in this way as well. I also used that info to figure out which scenes to upgrade, when I have had temporary access to a particular site. ie: Say you have a lot of 2160p files but get a new headset and want to replace those with 2700p versions.

Going a step further, being able to craft a filter that's like "site=Network && resolution < 4K" would be great, but that would require mapping all the various 4K-ish resolutions to a tag called "4K" (and ditto for tags like "5K" and "1600p" or whatever else. So I'd consider this a step beyond the basic level of displaying/filtering on raw values.

**Comment by jrebey** [comment]
The data is already stored. We just need a good way of exposing the data in the UI in an unobtrusive way.

https://github.com/xbapps/xbvr/blob/master/pkg/models/model_file.go#L23-L29

**Comment by cld9x** [comment]
I think such filter would make the most sense as a part of "files" UI, since in "scenes" view files are abstracted away.

**Comment by cld9x** [comment]
Also, resolution and bitrate is already mentioned in scene details view!

**Comment by vpfruitly** [comment]
lol, I knew I should have had it running and checked before typing out the whole ticket.

**Comment by jrebey** [comment]
Do you still need this now that we realized the data is already there? In your use case, you can even remove the file in the same UI. Once I submit a small bug fix :)

**Comment by vpfruitly** [comment]
Well, the file detail view doesn't expose bitrate, just resolution. But ideally it would be exposed in something like a table, rather than going into each file individually. I've got some thoughts on it, maybe it's something I could tackle when I get more familiar with the code.

**Comment by vpfruitly** [comment]
I'd say this is done. Every filter I'd want is in there. Can probably generate new issues if anyone thinks of another filter they wanted.
