### ISSUE TITLE
FuckPassVR not scraping

### ISSUE THREAD

**Issue by logics102** [xbapps/xbvr#1701]
New scenes aren't being scraped and covers seem to be broken upon attempted scrape.

**Comment by theRealKLH** [comment]
@logics102 @sharkysi You should be good after #1741 w/scraping. For the cover (and gallery) images missing... You need to mark the scenes for update and rescrape. This shouldn't be a scraper issue, but rather most likely due to the "expiration/token" parameters in the url.
