### ISSUE TITLE
Funscript causes silent crash

### ISSUE THREAD

**Issue by Mellified** [xbapps/xbvr#1745]
When xbvr tries to create a heatmap for the attached funscript there is a silent crash in xbvr. No errors are logged.

Removing the metadata before the actions allows xbvr to successfully create the heatmap. The specific metadata object in the JSON that causes the problem was not investigated.

This script came from https://discuss.eroscripts.com/t/slibowitz-scripts-production-a-tribute-to-teenyginger-self-made-joi-pmv/93732 but the script needs to be downloaded from the FapTap link mentioned in that post.

[A tribute to TeenyGinger - PMV.zip](https://github.com/user-attachments/files/15705989/A.tribute.to.TeenyGinger.-.PMV.zip)

**Comment by Mellified** [comment]
I've seen this issue with more funscripts. The commonality I've noticed is an underscore `_` character in the `"script_url"` metadata field - or perhaps the fact that this field is not a URL?

May not be the same code path as above, but has the same symptoms.

```
,"metadata":{"duration":167950,"notes":"","video_url":"","description":"https://github.com/ncdxncdx/FunscriptDancer","creator":"Procedurally generated using FunscriptDancer","script_url":"","title":"cyber-sex-pmv-hmv-with-lucario_1080p","performers":[],"license":"","tags":["music","audio"],"type":""},"version":1.0}
```

**Comment by swapsingh200** [comment]
Facing the same issue with ~6 other funscripts I have
