### ISSUE TITLE
[Bug] Some Scrapers Do Not Find Cover Images

### ISSUE THREAD

**Issue by cruisinpd** [xbapps/xbvr#1759]
I have tried scraping for 18vr, badoinkVR, VRcosplayX, KinkVR and a few others and they do not find any cover images. Most other scrapers do find cover images.

**Comment by theRealKLH** [comment]
one thing I recommend is to look through other open issues as well as open Pull Requests. This is already being addressed. PR #1754 will resolve this.

**Comment by cruisinpd** [comment]
Thank you for your help!
