### ISSUE TITLE
gDrive Support

### ISSUE THREAD

**Issue by mag-neat-oh** [xbapps/xbvr#181]
Would be great if xbvr had native support for cloud storage, but mainly gdrive since they have the most affordable and powerful storage solution. If xbvr could support strm files and the client could be made to direct play from gdrive, the bandwidth/cycles needed for xbvr alone could be low enough that it might be feasible to run the whole thing from a free gce vm.

**Comment by cld9x** [comment]
What is strm file?

**Comment by vpfruitly** [comment]
It's a KODI thing, I think: https://kodi.wiki/view/Internet_video_and_audio_streams#The_.STRM_file_method:

Aren't there applications at the OS level that allow mounting of cloud storage as if it were a local filesystem?

**Comment by cld9x** [comment]
As put.io integration proved, cloud service support makes a lot of sense, but in case of gdrive initial setup seems to be massive PITA.

Does anyone know about other tool that integrates with gdrive without need to take 50 steps first?

**Comment by theemfan** [comment]
I'm actually currently using Google Drive with XBVR with [rclone](https://rclone.org/)  

I' mount my Google Drive folder using rclone, and point XBVR to it, and everything just works. It even supports put.io.  

I think this isn't really an XBVR problem. Essentially, if you can mount a remote drive as a local drive, you've solved the problem.  

Here's [step-by-step instructions](https://github.com/PGBlitz/PGBlitz.com/wiki/RClone-Cache) to set up rclone with Google Drive.

**Comment by ChaosTherum** [comment]
Both rclone and then google file stream integrate with gdrive though I'm not sure about the source code accessibility of google file stream I know that rclone should be wide open. I'm a little surprised that there isn't already a go library for gdrive integration.

**Comment by theRealKLH** [comment]
@mag-neat-oh cleaning "dead" issues. Assuming this isn't an issue any longer.
