### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by SturmB** [xbapps/xbvr#1842]
I'm getting a "Method Not Allowed" message after XBVR scrapes a certain number of scenes from NaughtyAmericaVR. Here's a screenshot showing the logs when the error started.

![WindowsTerminal_AYv82ix2E8](https://github.com/user-attachments/assets/9ec055a2-61a8-4e25-9b63-bfaba6e8c4d1)

Do you know why this is happening and what can be done? Besides scraping one scene at a time, which I won't do because there are hundreds that have failed to scrape with this message.

**Comment by pops64** [comment]
Possible NA is rate limiting your requests. See here for instructions https://github.com/xbapps/xbvr/pull/1665
