### ISSUE TITLE
Feature request: filtering tags with AND operator.

### ISSUE THREAD

**Issue by DmytroSokhach** [xbapps/xbvr#1844]
**Problem:** 
current filtering is done with OR operator which adds more search results when more tags added

Solution:
filtering with multiple tags selected should apply AND operator between tags

Goal is to "refine" search, in other words narrow search results.

**Comment by tosh6072** [comment]
You should be able to do this now, the default is OR but you can click the Tag and it should turn Green to indicate the Tag must exist (i.e. AND) click it again and it will turn Red to include scene that do NOT include the Tag.  You can do this with other filters as well, eg cast, site, attributes.

Example: click "Brown eyes" and "Brown hair" green and you will only get scenes Tagged with both
