### ISSUE TITLE
DLNA server does not display scenes anymore

### ISSUE THREAD

**Issue by Sinoh726** [xbapps/xbvr#185]
from changes done in 0.3.0-beta.7 
DLNA server does not display any content associated to scenes anymore. 
Only unassigned files are displayed in DLNA

**Comment by jrebey** [comment]
What version were you coming from? I'm not seeing anything in the changes in 0.3.0-beta.7 that would cause this.

**Comment by Sinoh726** [comment]
from version 0.3.0-beta.6

**Comment by jrebey** [comment]
So it worked in 0.3.0-beta.6 but not 0.3.0-beta.7? How are you running XBVR and on which OS?

**Comment by Sinoh726** [comment]
win10 64bit running in admin mode (tried both modes normal and admin).

**Comment by jrebey** [comment]
I don't have Windows but I can check to see if it works under Linux at least. That'll tell us if it's a problem everywhere or just Windows. If it works for Linux, I'll have one of the dev's who uses Windows take a look.

**Comment by jrebey** [comment]
Confirmed this isn't working. Only the unmatched folder has any content.

**Comment by crwxaj** [comment]
This was fixed by https://github.com/xbapps/xbvr/commit/d369f7b2bb6e3fb10d1eef24d8cfff861576ba80
