### ISSUE TITLE
[Feature Request] Add BrazzersVR Scrapers

### ISSUE THREAD

**Issue by SerJonSnow** [xbapps/xbvr#1860]
It looks like Brazzers has finally committed to a proper VR website. They've added all their old 5k videos and even have a few new 8k ones. Would it be possible to have a scraper added for this site?

https://www.brazzersvr.com/videos

**Comment by pops64** [comment]
What is the members link to the scene page if any?

**Comment by SerJonSnow** [comment]
https://site-ma.brazzersvr.com/scenes

I think the above link is probably the one you're looking for?

There's also the main landing page here if that's any help: https://site-ma.brazzersvr.com/scenes

**Comment by pops64** [comment]
Yes thanks. The public facing link is different than those that subscribe. I just need to confirm cause XBVR has the ability to list the members link. Just need to where the members url is.

**Comment by SerJonSnow** [comment]
Sounds good, let me know if you need anymore info at all!

**Comment by pops64** [comment]
The file name convention we have is `<scene title>_<resolution>.mp4` were white space is replaced with `-` does this also work for Brazzers?

**Comment by SerJonSnow** [comment]
Looks like it! I believe they follow the same naming scheme as VirtualPorn (Bangbros). I've added a couple of file titles below:

sauna-sex_2880p
dirty-talking-escorts_3840p
a-threesome-with-two-mistresses_3840p
