### ISSUE TITLE
NaughtyAmericaVR Scenes not scraping

### ISSUE THREAD

**Issue by sharkysi** [xbapps/xbvr#1866]
Scenes havent scraped for last two weeks

**Comment by pops64** [comment]
NA is known to be aggressive with there DDoS protection. You most likely have tripped this. They use a captcha request to unblock the connection. Use a VPN to get around this or turning off the scraper for a bit might undo this. With NA either use limit scraping or rate limit the request per min to NA to prevent this. #1665
