### ISSUE TITLE
"Data too long for column 'image_url'" with VirtualRealPorn

### ISSUE THREAD

**Issue by SturmB** [xbapps/xbvr#1873]
When scraping VirtualRealPorn, after a few dozen scenes are scraped, I get this message, and the Docker container restarts.

![WindowsTerminal_DPz6DyCbIM](https://github.com/user-attachments/assets/6689a2e1-9202-47db-9bcc-705c490c5fba)

This seems to be similar to #1623. Perhaps a similar solution (#1658) of increasing the data size of that column would help?

**Comment by pops64** [comment]
If your using MariaDB make sure it is setup correctly. There are instructions in the Wiki and additional info can be found searching the discord server. Also make sure your XBVR is updated. You may have corrupted Virtual Real Porn data which may call for a wipe

**Comment by SturmB** [comment]
I'm not sure I'd even be able to use XBVR if I had set up MariaDB incorrectly. I followed those Wiki instructions to do so. And I use Pullio to ensure that XBVR is always kept up to date. I don't relish starting from scratch again, but I may give that a try in the near future.

**Comment by pops64** [comment]
It would just be virtual porn that may be corrupted. You can always backup your DB before attempting a restart. I would check discord as there are additional steps that aren't the wiki that are recommend todo with Maria

**Comment by SturmB** [comment]
Here's a solution that worked for me.

1. Shut down both your XBVR and MariaDB containers, then delete them.
2. Edit your `docker-compose.yml` file and add the following line to your MariaDB service: `command: --sql_mode="NO_ENGINE_SUBSTITUTION"`.
3. Recreate and start both containers.
4. In XBVR, click the vertical ellipsis next to the scraper you were having trouble with and choose "Force update scenes." Then click that same ellipsis and choose "Run this scraper" or wait until the next scheduled scrape.

I have updated the Docker Compose file instructions in the wiki.
