### ISSUE TITLE
Docker container issues - 0.3.0-beta-7

### ISSUE THREAD

**Issue by aelius12** [xbapps/xbvr#192]
First of all, a big thank you to all the devs for making XBVR a reality.
I use XBVR as a docker container, but the latest release **beta 7** presents some issues that were not present in previous ones. I didn't find a similar issue report on this, so here it goes.

Using the current instructions for docker, the "xbvr:latest" tag gives an error:
`docker: Error response from daemon: manifest for xbapps/xbvr:latest not found: manifest unknown: manifest unknown.`
Setting manually the version worked fine with **beta 6**. However, with **beta 7**, this error now prevents XBVR from starting:
` /xbvr: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by /xbvr)`
I've seen there were deeper changes to the docker container creation setup, but I'm not familiar enough with Docker to understand what might the problem be, or if I'm doing something very silly.
Thank you and regards.

(If helpful, tested on an archlinux x86 system with a working docker)

**Comment by jrebey** [comment]
I’m looking into why this is happening in drone based builds. I’ll setup a drone project and see if I can fix it. I have a few ideas.

If I can’t fix it before the next release, I’ll revert the containerless change in the drone dockerfile.

**Comment by aelius12** [comment]
Super. Thank you for looking into this.
