### ISSUE TITLE
Manual matches don't appear in scenes until you re-run the "Rescan" under Files.

### ISSUE THREAD

**Issue by vpfruitly** [xbapps/xbvr#229]
Couldn't really think of a short but accurate summary for the title, so the title says it all. You scan files, you scrape scenes, you make matches, but they don't appear until you hit rescan.

**Comment by jrebey** [comment]
I think this is because matching a scene doesn't flip the is_available and/or is_accessible bits on the scene.

**Comment by vpfruitly** [comment]
I think that happens here: https://github.com/xbapps/xbvr/blob/aab0e15e09ef85b0c09abd91c4c5cd2d7c71dda8/pkg/xbvr/api_files.go#L232
