### ISSUE TITLE
File matching does not distingish same title for different studios

### ISSUE THREAD

**Issue by razfag** [xbapps/xbvr#233]
If scenes with an identical title are present the respective files are incorrectly matched to the last one.

for example
```SQL
select files.id as file_id, files.scene_id, files.filename, scenes.site
from files 
join scenes on files.scene_id = scenes.id 
where scenes.title = 'Taco Tuesday';
```
|file_id|scene_id|filename|site|
|--|--|--|--|
|2621|453|WankzVR-Taco-Tuesday-1920p-180_180x180_3dh_LR.mp4|18VR|
|2790|453|18VR_Taco_Tuesday_samsung_180_180x180_3dh_LR_.mp4|18VR|

Also renaming one file and matching it manually is overridden once scenes are matched again (The _ in the second file.)

**Comment by jrebey** [comment]
Did you match the file in the UI and then manually unmatch it?

The problem with this is that as a convenience, the filename is attached to filenames_arr in scenes table. The next time files are scanned for matches, they are detected in filenames_arr.

I don't have a good way of fixing this without requiring everyone to do a full scrape of all scenes so we can move the user matched filenames out of filenames_arr and into their own column.

For now, you can remove the offending file from filenames_arr in the scenes table for scene_id 453.

**Comment by razfag** [comment]
Yes for this example it did resolve it.
However I do wonder why the title plays a role in scene matching in the first place.
Since the original filenames are known from scraping and every other filename is based on user input I would think it would completely ignore the title.
Couldn't it match just based on scenes.filename_arr, files.filename, scenes.id & files.scene_id?

**Comment by jrebey** [comment]
AFAIK, title doesn’t play a role in matching.

When you manually removed the filename from filenames_arr and zeroed out the scene id was xbvr stopped?
