### ISSUE TITLE
File location not being scanned?

### ISSUE THREAD

**Issue by jwvanderbeck** [xbapps/xbvr#255]
I have added a storage location, in my case `G:\APO-VR`.  It shows in the interface, and shows as "Available" but it never scans any of the files in there and I see no buttons to manually tell it to do so.

![image](https://user-images.githubusercontent.com/161126/75082178-402ae700-54c7-11ea-9988-7f44d764181e.png)

**Comment by Sinoh726** [comment]
Hello. Have you tried pressing "Rescan" button just bellow horizontal line on picture? 
![image](https://user-images.githubusercontent.com/57528642/75105917-331e0d00-5619-11ea-9dbd-81d1d866bcfb.png)

**Comment by jwvanderbeck** [comment]
Wow facepalm.  How did I totally not see that button until you pointed it out?!
