### ISSUE TITLE
'Esc' behavior modifications for overlays

### ISSUE THREAD

**Issue by anon-xbvr** [xbapps/xbvr#263]
From the 'Scenes' view, clicking on a scene will bring up an overlay with additional information about the scene (video player, Gallery, Files, etc.).  Pressing 'Esc' will remove the overlay and return to the 'Scenes' view.

Clicking on an image in the 'Gallery' will have an additional overlay with the image from the Gallery.  Currently, pressing 'Esc' in this will remove both the Gallery image overlay AND the scene detail overlay.

Would it be possible to change the behavior such that pressing 'Esc' only exits the Gallery image overlay, and returns the view to the scene detail overlay?

**Comment by cld9x** [comment]
There's an issue with keypress events handling, you can temporarily use `g` to trigger gallery on/off instead
