### ISSUE TITLE
Unable to scrape new scenes due to database locking issue

### ISSUE THREAD

**Issue by jrebey** [xbapps/xbvr#274]
There are multiple calls to GetDB during a scrape, particularly when scrapers finish and log their status.

The UI gets stuck when this happens and I see the following in the logs:

time="2020-05-10T04:45:02Z" level=fatal msg="failed to connect databasedatabase is locked"
(/go/appsrc/pkg/models/model_site.go:18) 
[2020-05-10 04:58:31]  database is locked

The daemon then panics and shuts down.

I've been unable to complete a scrape in weeks. If I go back to an old build (like beta 9 or something) it works... but obviously the scrapers are old. This may be due to a gorm library update after beta9.

I had sent a PR which sorta fixed it by using a channel for logging, which worked on one of my machines but didn't seem to fix it on the other so I closed it. Reverting gorm to the previous version and then recompiling with the latest go version seems to make it better, but it still happens occasionally. Perhaps the combination of scraper logging via channel and gorm/golang changes might fix it... not sure.

I'm running xbvr beta21 via docker.

**Comment by cld9x** [comment]
Thanks for bringing this up with more details - I’ve been getting reports about that issue, but couldn’t replicate the problem in any environment (including docker).

Gorm isn’t as big problem as it underlying SQLite integration which is tied to Go’s database/sql and its need to pool database connections (which is worst idea possible in case of SQLite).

Could you run app with DEBUG flag and share some logs?
