### ISSUE TITLE
possibility to delete manualy created Smart playlist

### ISSUE THREAD

**Issue by Sinoh726** [xbapps/xbvr#275]
After creating several smart playlists (also for testing purposes) it would be good to have posibility to delete them if needed.

**Comment by cld9x** [comment]
UI for playlists is coming

**Comment by lockedmouse** [comment]
This got implemented in 0.3.6 (6b7107f2364571cc6772c94941e5a5d51ac4be0e), so this issue can be closed.

**Comment by theRealKLH** [comment]
@Sinoh726 cleaning "dead" issues.
