### ISSUE TITLE
Display expected filename of "Not Downloaded" scenes

### ISSUE THREAD

**Issue by yep-it-not-me** [xbapps/xbvr#284]
XBVR provides information about scenes that have not been found at the storage paths provided. It would be nice if it could show more information, specifically potential file names, for the missing scenes. 

This would allow the user to search other, unscanned, storage locations for the missing files, move things around as needed, and get the library organized / completed.

This could be implemented in the scene popup. The existing "Files" list could list all known filenames for the scene, and then indicate which ones are found and which ones are missing. Missing files greyed out, or similar. 

This approach would also allow users who need to track different versions / resolutions of the same scene to do so from the existing popup.

**Comment by yep-it-not-me** [comment]
In the case of a scene that *is* downloaded, this change could let the user know there are higher (or lower) quality versions available.

**Comment by cld9x** [comment]
Not a big fan of that idea: it's either zero known filenames, or myriads - so adding that to "files" tab is off the table.

I think good middleground option would be "debug" option showing all of the scene info as it's stored internally.

**Comment by yep-it-not-me** [comment]
I like the idea of some kind of a 'all data' view. "Let me know everything you know about this scene" would be super useful.

**Comment by yep-it-not-me** [comment]
I think this is addressed with the "Filenames" view when editing a scene.
