### ISSUE TITLE
How to change cache folder?

### ISSUE THREAD

**Issue by gino8080** [xbapps/xbvr#290]
is there a way to change the cache folder instead of using USER/appData/Roaming/xbvr ??

**Comment by cld9x** [comment]
At the moment no, but this is relatively quick one as long as we assume it a hidden setting dedicated for users who know what they are doing

**Comment by jrebey** [comment]
What’s the rationale for changing it?

**Comment by Aerowen** [comment]
Not OP but I'd like to see this option as well at some point. Currently (on windows) the app uses user/appdata/roaming/xbvr on the C: drive to store its cache even if you have the xbvr.exe on a different drive. Considering the cache folder can grow quite big that's not always wanted. For me it's close to 30.000 files and already over 5GB, I'd rather not have a cache that big and constantly growing on my M.2 SSD c-drive.

**Comment by vpfruitly** [comment]
This can be done on Windows easily already, provided you know the undocumented setting to change. Here's an example bat/cmd file that accomplishes what you want:

```
@ECHO OFF
set APPDATA=S:\OtherDrive\OtherFolder\WhateverYouWant\
cd S:\OtherDrive\OtherFolder\WhateverYouWant\
start xbvr.exe
```
