### ISSUE TITLE
MILFVR scraper with no scenes

### ISSUE THREAD

**Issue by atani12** [xbapps/xbvr#291]
A week ago I started with a fresh docker XBVR container but MILFVR doesn't get updated with scenes. The log shows 1 page on MILFVR being scraped and then straight to `updating tags`, where it adds no scenes. WankzVR shows no problems.

Anyone else has this issue?

Thank you for the amazing work with XBVR

**Comment by fauxtographe** [comment]
I'm having the same issue as well.

**Comment by Aerowen** [comment]
Their site has changed a few things so the scraper needed fixing. I've made the fixes but can't test them at the moment because I'm getting some unrelated error in a different file so it won't build. Once that gets fixed I'll submit fixes for this scraper.

**Comment by atani12** [comment]
The problem seems to continue with newest version beta-28.
There's around 16 scenes that get added from MILFVR, wether with a force update or not, but that's it. The list of 16 is always the same and is the most recent videos.
