### ISSUE TITLE
NaughtyAmerica Scraper Crashing XBVR

### ISSUE THREAD

**Issue by fauxtographe** [xbapps/xbvr#293]
XBVR crashes for me after a few seconds when I try to run the NaughtyAmerica scraper. The XBVR icon just disappears from the menubar without any message. At that point, the server UI is non-functional from the browser, and XBVR has to be relaunched.

**Comment by Aerowen** [comment]
Their site has changed a few things so the scraper needed fixing. I've made the fixes but can't test them at the moment because I'm getting some unrelated error in a different file so it won't build. Once that gets fixed I'll submit fixes for this scraper.

**Comment by atani12** [comment]
No crashes occur with the latest beta-28, but the scraper cannot get covers for scenes released after the website changes.

**Comment by Aerowen** [comment]
I do get covers for scenes so it seems to be working correctly for new scenes that weren't scraped yet.
Perhaps you already had those scenes scraped before updating to beta-28 which might need you to do a forced update? (To do this: On the scrapers page, click on the ⋮ icon, choose "force update scenes".) That should update the covers.

**Comment by Aerowen** [comment]
Thanks for reporting this, apparently NAVR uses the new video player only for the four most recent scenes. So as new scenes are released it changes again on the older ones. I had assumed they had switched over to a new video player entirely... oh well. Fixes are submitted, for MilfVR as well, I overlooked a mistake causing it to only scrape page 1, oops.
