### ISSUE TITLE
UI Improvement Request

### ISSUE THREAD

**Issue by Kaylakaze** [xbapps/xbvr#298]
Can more information be added to the SceneMatch view? One helpful item would be the file path (you can put it below the file name just like how it is in the file list). Also, the ability to skip to the next video if no match is found would help a lot.

EDIT: NVM on the second part there. I just noticed the arrows on the side of the screen. I'm running at 4k and they're not very noticeable when you're looking at the dialog box.

**Comment by dan9qt** [comment]
I agree about the file path. Would be very useful to me due to my filing system.
