### ISSUE TITLE
Problems with using prev/next buttons for scenes

### ISSUE THREAD

**Issue by SpedNSFW** [xbapps/xbvr#326]
In the scenes view when a scene card is open, using the prev/next buttons can cause problems.

1. The gallery does not get updated and can stay on the previous scene's gallery.

2. Changing what image is active in the gallery before changing scenes will change the active image on the next instead of resetting to the first image.

**Comment by vpfruitly** [comment]
Yeah, I'm seeing this too. It seems to have either started sometime in the last few builds or has gotten worse.

**Comment by SpedNSFW** [comment]
So this happens when you go from a scene with a greater number of gallery images than the one you're switching to.
