### ISSUE TITLE
Manually matched scenes are unmatched after rescan

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#341]
Manually matched scenes data is not saved

**Comment by SpedNSFW** [comment]
Can you provide any information for this? Did you move or rename the files? When you manually match a scene, the filename is added to the scene's list of filenames so it knows the file is that scene.

**Comment by theRealKLH** [comment]
@Deflated-Criossant cleaning "dead" issues. Assuming this was resolved by one of the various "re-apply edits" PRs.
