### ISSUE TITLE
Docker image with tag `latest`

### ISSUE THREAD

**Issue by CoolMintChocolate** [xbapps/xbvr#360]
Hi,

The README specifically says that we should be using the `xbapps/xbvr:latest` image for our Docker set up, but as far as I can tell the `latest` tag does not exist. I have to use `0.3.0-beta.32` instead. Is there any chance you can tag that (and later releases) as `latest` please?

Thanks!

**Comment by theRealKLH** [comment]
@CoolMintChocolate I believe this has finally been resolved.

**Comment by CoolMintChocolate** [comment]
Yup it certainly has. Thank you!
