### ISSUE TITLE
MacOS Release Package Issues - Fixes not being merged?

### ISSUE THREAD

**Issue by riley1234sd** [xbapps/xbvr#363]
I've had some issues with the last 4-5 or so versions of the MacOS package (ex: downloading and installing xbvr_0.3.0-beta.32_macOS_amd64.zip) with some specific scrapers outlined below.

Certain release notes mention fixes for these issues (i,g. 0.3.0-beta.29 saying it fixes NAVR and MilfVR scrapers, 0.3.0-beta.31 'Merge WankzVR and MilfVR scrapers') but they don't seem to be resolved on my install/machine using the macos package. Others in discord mention no issues with these scrapers?

I've provided a video of a brand new fresh install of XBVR 0.3.0-beta.32 MacOS on my mac machine showcasing the problems. Video: https://www.dropbox.com/s/wln0n32vozp5ybh/example.mov?dl=0

Issues
- WankzVr scraping no scenes (video timestamp 00:00-00:25)
- MilfVR scraping no scenes (video timestamp 00:26-00:34)
- NamVR scraping scenes, tags but not images or scene titles (video timestamp 1:25-10:35)
- VirtualTaboo scraping no scenes (video timestamp 12:34-13:15)

I've included some video time showing this build working fine for other scrapers (Little Caprice video timestamp 00:38-1:05) (VR Solos video timestamp 10:59-12:30) so It makes me question if it's my machine/internet and not the app itself.

Any help would be appreciated...even if that advice is dropping the MacOS package route for the Docker route. I'm not very technical so have been resorting to this more consumer friendly approach...and if my problem is not unique to my machine/internet then I'm sure others might be running into it and it would be good to make you aware of the issue.

Thank You!

**Comment by JohnWayneTracy** [comment]
I'm also having this issue with my MacOS machine, and saw a post on the Discord from someone else who seemed to have the same issue. I wondered if it was just my machine or internet as well. I've not yet tried the Docker route yet.

**Comment by theRealKLH** [comment]
I had responded to the person on Discord that I wasn't seeing the issues. I downloaded fresh on to a Mac (High Sierra) and everything worked. I also just now on a fresh MacOS Catalina VM just ran a fresh compile to test changes to fix VirtualReal sites. No issues. Regarding NaughtyAmerica, the "no title" is known. I believe someone mentioned that the website doesn't have titles for it's videos.

Can you guys drop to terminal and run xbvr from there....

 `/Applications/XBVR.app/Contents/MacOS/xbvr`

that should provide some output so you can see what's (not) happening at the time.

**Comment by JohnWayneTracy** [comment]
[0056]  INFO Scraping started at Thu Sep 24 12:35:22 2020 task=scrape
[0056]  INFO Lost 8191759441113474
[0074]  INFO Starting WankzVR scraper completed=false progress=0 scraperID=wankzvr started=true task=scraperProgress
[0074]  INFO visiting https://www.wankzvr.com/videos?o=d
[0074]  INFO Finished WankzVR scraper completed=true progress=0 scraperID=wankzvr started=false task=scraperProgress
[0074]  INFO DONE task=scraperProgress
[0074]  INFO Updating tag counts task=scrape
[0095]  INFO Lost 3644740176026369
[0095]  INFO Building search index... task=scrape
[0096] ERROR document ID cannot be empty

**Comment by theRealKLH** [comment]
Not much there. was hoping for an actual error. This is what I get...

```
[0054]  INFO Scraping started at Tue Sep 29 18:29:10 2020 task=scrape
[0054]  INFO Lost 4556901065285123
[0054]  INFO Starting WankzVR scraper completed=false progress=0 scraperID=wankzvr started=true task=scraperProgress
[0054]  INFO visiting https://www.wankzvr.com/videos?o=d
[0055]  INFO visiting https://www.wankzvr.com/videos?o=d&p=2
[0055]  INFO visiting https://www.wankzvr.com/videos?o=d&p=3
[0055]  INFO visiting https://www.wankzvr.com/videos?o=d&p=4
[0056]  INFO visiting https://www.wankzvr.com/videos?o=d&p=5
```
Silly question.. can you actually browse to that page? "https://www.wankzvr.com/videos?o=d"

You could also try this "not official" version..
[xbvr_0.3.0-unoffical_macOS_amd64.zip](https://github.com/xbapps/xbvr/files/5302275/xbvr_0.3.0-unoffical_macOS_amd64.zip)

**Comment by riley1234sd** [comment]
thanks for the troubleshooting theRealKLH and JohnWayneTracy.
OP here chiming back in.

I've tried the "not official" version you posted and am running into all of the same errors from the OP. The terminal string you posted two posts back return the below on the "not official" version on my machine.

Seedboxs-MacBook-Pro:~ seedbox$ /Applications/XBVR.app/Contents/MacOS/xbvr
2020/09/30 09:36:43 ffprobe and avprobe not found in $PATH
[0000]  INFO Migration did run successfully
[0000]  INFO Starting router
[0000]  INFO Added realm: default
[0000]  INFO XBVR 0.3.0-beta.32 (build date 2020-09-23T02:26:34Z) starting...
[0000]  INFO Web UI available at http://127.0.0.1:9999/, http://192.168.0.202:9999/
[0000]  INFO Web UI Authentication enabled: false
[0000]  INFO DeoVR Authentication enabled: false
[0000]  INFO Using database: sqlite:/Users/seedbox/Library/Application Support/xbvr/main.db
[0000]  INFO Starting DLNA
2020/09/30 09:36:43 HTTP srv on [::]:1338
2020/09/30 09:36:43 started SSDP on en0
2020/09/30 09:36:43 started SSDP on lo0

Happy to jump in with any other testing LMK

**Comment by theRealKLH** [comment]
@riley1234sd what do you see when you try scraping. What you are showing is only what's shown when you first launch xbvr. You should at least have under the last line a "lost" entry like [0095] INFO Lost 3644740176026369... I believe that happens each time you hit/refresh the Scenes page in browser.

**Comment by theRealKLH** [comment]
Just saw your post. What did your last post say? Was it the output in terminal when doing a "failed" scrape? Still need to see that to narrow down what might be the problem/possible fix.

**Comment by riley1234sd** [comment]
@theRealKLH Thanks. I'm going to post a link to the terminal log data since when I posted in here last time it seemed to get me suspended/flagged.

Scrape log here: https://www.dropbox.com/s/w3fk7nero3ll5cz/xbvr_output.txt?dl=0

Where scrapes begin in the log:
0283 = Start of MilfVR scrape
0469 = Start of WankzVR scrape
0661 = Start of VirtualTab scrap
0896 = Start of Naughty America scrape

This scrape is all on 0.30 beta.34 build. The same issues still apply as they have been on the last handful of versions: 
- MVR, WVR, VT all don't pull ANY data (nothing to match files against, with no sign of scrape error in the log). I performed the scrapes you see in the log after doing a 'Delete Scraped Scenes' and 'Force Update Scenes' for each site.
- NAMVR DOES pull scene tags and release date, but no scene title, thumbnail or images. I performed the scrapes you see in the log only after doing a  'Force Update Scenes' (I don't want to lose all of my matches by doing Deleting Scraped Scenes).

Appreciate any further eyes and help with this issue.

**Comment by theRealKLH** [comment]
wow.. just saw this. don't remember getting a notification... Anyways, that log doesn't show anything either. It's strange that it is only hitting the first link then "moving on". Have you tried with new database? just rename the existing one to test. 

regarding NAMVR.. you are getting expected output. NO TITLES.

**Comment by riley1234sd** [comment]
thank you @theRealKLH. I'm away and had to tear down my DLNA for a bit...probably until the new year. I'll follow up when I can test your solution.

RE: NAMVR I also get no scene cover, secondary images - is that correct? I don't care much about names but mostly the scene covers.

**Comment by JohnWayneTracy** [comment]
New update: MilfVR pulls data! But WankzVR and VT still does not. 

NAMVR -- I can get scene tags and release date, but no title, cover, or anything else to indicate what the scene is. Is this the current status for everyone or just the status of our little corner of Mac OS issues?

I just reinstalled to verify this was still the issue. I've previously done a scrape in a build run in Docker, and pulled the scraped info for WankzVR and VT into the file. This at least allows me to get scene tags and release dates, though it didn't seem to pull the images for the scenes.

**Comment by theRealKLH** [comment]
@JohnWayneTracy So you are saying... "works in Docker" "not in MacOS"????

**Comment by JohnWayneTracy** [comment]
@theRealKLH That's correct! It worked when I ran it in Docker, and I just pulled all the cached files and copied into the MacOS build's folders.

That works for anything released UP TO that moment. I still cannot scrape **new** files, released after the most recent Docker scrape.

**Comment by riley1234sd** [comment]
@theRealKLH @JohnWayneTracy My DLNA is back online (yes!) and can confirm I'm having the same issues as @JohnWayneTracy on Jan 7 2021. MilfVR is now working, no Wankz or VT, and NAMVR still no images.

@theRealKLH I tried renaming my .db to 'test' to try fresh and ran into the same issues

**Comment by JohnWayneTracy** [comment]
@theRealKLH @riley1234sd Update: With the last two releases, I've been able to scrape everything, including NAMVR, with covers -- EXCEPT VT. No scraping actually occurs as far as I can tell (starts and immediately completes), as it did with Wankz before. 

But everything else works, and that's fantastic.

**Comment by JohnWayneTracy** [comment]
@theRealKLH Just following up here: everything works, except VirtualTaboo. Has not worked for the past few builds.

**Comment by riley1234sd** [comment]
yep same here @theRealKLH @JohnWayneTracy - been loving everything working (but taboo). such a great experience.

**Comment by riley1234sd** [comment]
@JohnWayneTracy are you still having issues with virtualtaboo?

**Comment by theRealKLH** [comment]
@riley1234sd Assuming it was fixed by the root certificates updates? If yes, @JohnWayneTracy... update your root certs. [https://apple.stackexchange.com/questions/422332/how-do-i-update-my-root-certificates-on-an-older-version-of-mac-os-e-g-el-capi](url)

**Comment by JohnWayneTracy** [comment]
I don't have a modern MacOS system unfortunately to be able to copy those certificates from. I was able to fix the most recent certificate expiration, but that hasn't changed the scraping issue. I am able to access the site directly, regardless.

**Comment by theRealKLH** [comment]
@riley1234sd cleaning "dead" issues.
