### ISSUE TITLE
VirtualRealPorn no longer scraping correctly

### ISSUE THREAD

**Issue by halinc** [xbapps/xbvr#366]
VirtualRealPorn seems to be no longer scraping correctly. It is accessing the site and getting the details, but only the last scraped scene is shown in XBVR

**Comment by theRealKLH** [comment]
PR #365 was submitted for this issue.

**Comment by theRealKLH** [comment]
Also, before anyone thinks the scraper is STILL broke after changes are merged.... VRealPorn doesn't think Julia Parker (Farmers Market) is "Female" and VRealTrans doesn't think Luana Costa (My Sweet Lollipop) is "Transgendered". So they are not tagged.
