### ISSUE TITLE
BadoinkVR Network Filenames

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#367]
https://github.com/xbapps/xbvr/blob/822eac0e3950831e86c46baebbe3c8ff88fe3d6a/pkg/scrape/badoink.go#L103

**Add support for new 4K HEVC and PSVR formats**
Applicable to all Badoink network sites

```
mobile_180_180x180_3dh_LR.mp4
mobile_low_180_180x180_3dh_LR.mp4
samsung_180_180x180_3dh_LR.mp4
4k_HEVC_180_180x180_3dh_LR.mp4
5k_180_180x180_3dh_LR.mp4

ps4_180_sbs.mp4
ps4_pro_180_sbs.mp4
```

Eg: BadoinkVR_Gianna_Dior_4k_HEVC_180_180x180_3dh_LR.mp4

![bdk file formats](https://user-images.githubusercontent.com/16240121/95669505-1aaa3500-0b9f-11eb-90a6-f7991c23457e.jpg)
![Screenshot_76](https://user-images.githubusercontent.com/16240121/95669534-855b7080-0b9f-11eb-8d5a-e4814b1c26fa.jpg)
![Screenshot_75](https://user-images.githubusercontent.com/16240121/95669535-868c9d80-0b9f-11eb-95fb-acdf7e82a137.jpg)
![Screenshot_74](https://user-images.githubusercontent.com/16240121/95669536-87253400-0b9f-11eb-93c8-4d47b80872b2.jpg)

**Comment by theRealKLH** [comment]
What "support" is being asked for (by adding the updated formats)?

Scraping/matching? ... If all files are coming down as "BadoinkVR_Gianna_Dior_xxxxxxxxx.mp4" adding new "video formats" isn't going to help scraping. Unless I'm missing something. You got a 50/50 chance of getting the match right (automatically or manually), no matter if it's 4K, 5K, samsung, etc.

You will still need to manually intervene. Either changing the name to "BadoinVR_Door_to_Dior_xxxxxxx.mp4" prior to automatching happens or choosing which video you downloaded during manual matching, as you are showing which leads back to "it doesn't matter about the additional formats" GRIN.

Are any of these sites actually auto matching during scans?
