### ISSUE TITLE
Build fails with v33/34

### ISSUE THREAD

**Issue by atani12** [xbapps/xbvr#370]
Dear XBVR devs,

Thank you a million for this excellent way of organising VR porn videos. Love it.

I have 2 docker containers of XBVR for distinct databases of content and make use of DLNA, so once in a while I change the DLNA and website ports of a release and build the Dockerfile for a new image.
Since trying this week building from the Dockerfile, I always end up with this error:

```The command '/bin/sh -c curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar -xzv && go get -u -v github.com/acroca/go-symbols github.com/cweill/gotests/... github.com/davidrjenni/reftools/cmd/fillstruct github.com/fatih/gomodifytags github.com/haya14busa/goplay/cmd/goplay github.com/josharian/impl github.com/nsf/gocode github.com/ramya-rao-a/go-outline github.com/rogpeppe/godef github.com/uudashr/gopkgs/cmd/gopkgs github.com/zmb3/gogetdoc golang.org/x/lint/golint golang.org/x/tools/cmd/godoc golang.org/x/tools/cmd/gorename golang.org/x/tools/cmd/guru sourcegraph.com/sqs/goreturns github.com/UnnoTed/fileb0x' returned a non-zero code: 2```

Any idea how that error can be surpassed to create a new docker image?

Tried building from local Archlinux system and Docker Hub, same results

**Comment by atani12** [comment]
I realise website ports can be set by editing the SQLite database, but not DLNA. As `network: host` is needed for docker and I have 2 running simmultaneously, only one shows, hence the Dockerfile build need.
But if you know of another way around that, that would be even better.

Thank you again :100:

**Comment by atani12** [comment]
Issue remains with v34

**Comment by theRealKLH** [comment]
you can pull iamklh/xbvr:notofficial for now.

**Comment by joojoodamn** [comment]
Thanks

**Comment by atani12** [comment]
Thanks @theRealKLH

**Comment by joojoodamn** [comment]
We are defimatly on the same page right now. We have been ready!

**Comment by atani12** [comment]
Sorry to bother you again @theRealKLH 

I'm starting a new db for r18 content to get rid of the date issue, and was wondering if your latest docker build included that fix?

Thank you

**Comment by theRealKLH** [comment]
@atani12 JUST seeing this... sorry. Yes it does (in case you didn't try already). ALSO.. .35 was just released

**Comment by atani12** [comment]
No worries, I've been using it for a while already with a fresh db and it has been great having the content neat and correct.

Many thanks for the container and all the work you've been doing with XBVR :bow:

**Comment by theRealKLH** [comment]
I also changed the description on DockerHub.. added (Vxx) since it's not totally automated, a new release might be out for a while before I can update the container (it's not automatically updated at the moment).

**Comment by atani12** [comment]
Fixed with v35

Thank you :)
