### ISSUE TITLE
Button to go to the site's video page

### ISSUE THREAD

**Issue by yep-it-not-me** [xbapps/xbvr#376]
As I'm going through my collection in xbvr, looking at one scene entry, it would be awesome if there was a button I could push to go to that site's page for the video I'm looking at in xbvr. That way I could go download videos I don't have, or get other versions / resolutions easily.

**Comment by yep-it-not-me** [comment]
I see this can be done from the scene edit page now. Maybe it would be easier to just link the video title to the scene URL?

**Comment by atani12** [comment]
The video title is already a link to the site's video page.

**Comment by yep-it-not-me** [comment]
I was hoping to have the link in the detail view, but from the main page works too I suppose.
