### ISSUE TITLE
R18 Scraper: Incorrect Dates

### ISSUE THREAD

**Issue by c62624** [xbapps/xbvr#377]
The R18 scraper works fine, except the dates are wrong. 

Patterns I have noticed:
- The day of the month is always correct.
- The year is always one behind.
- If the original release date is not in May, September, or December, the above two things happen. Otherwise, the month is incorrect in addition to the year. (Not sure about February and April)
- If the release date is in December, than only the year will be incorrect, 1 behind.
- All the scenes with incorrect dates are assigned anywhere from 11/30/XXXX-1 TO 12/31/XXXX-1 where XXXX is the correct release year.

Here is an example of how the release date is displayed for every month on R18, using an example random scene for each month.
Dec. 27, 2019
Nov. 02, 2020
Oct. 22, 2020
**_Sept. 30, 2020_**
Aug. 28, 2020
**_July 31, 2020
June 24, 2020
May 28, 2020_**
Apr. 29, 2020
Mar. 27, 2020
Feb. 27, 2020
Jan. 28, 2020

**An example JAV scene that scrapes the incorrect scene is CBIKMV-058.**

I think the issue is Goment is not parsing the months correctly due to the different formats not matching the month token format. Maybe some conditional statements are needed for the months May, June, July, and September.

xbvr/pkg/scrape/r18.go 
line 52
`tmpDate, _ := goment.New(strings.TrimSpace(e.Text), "MMM. DD, YYYY")`

**Comment by theRealKLH** [comment]
So I was able to get this working locally, but testing on Gitpod the date is off by one day.

**Comment by c62624** [comment]
> So I was able to get this working locally, but testing on Gitpod the date is off by one day.

I’ve had that off by one day problem on other scrapers as well. Not sure what causes that.

I’d say just having at least the month and year correct would be a huge help even with the date being off by one.

**Comment by theRealKLH** [comment]
ok. I will submit PR shortly.
