### ISSUE TITLE
Fix KinkVR Scraper

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#379]
`KinkVR_Snow_Squirming_Slave_1M_mobile-low_180_180x180_3dh_LR.mp4_oculus_180_180x180_3dh_LR.mp4`

should be `KinkVR_Snow_Squirming_Slave_oculus_180_180x180_3dh_LR.mp4'

Remove '_1M_mobile-low_180_180x180_3dh_LR.mp4'

![Screenshot_95](https://user-images.githubusercontent.com/16240121/98376716-e4f74f80-2069-11eb-9918-f7f0978b76fa.jpg)

**Comment by theRealKLH** [comment]
BaDoink Network appears to have done a web redesign since I added the new formats for #367
