### ISSUE TITLE
No tags from VRBangers scraper

### ISSUE THREAD

**Issue by yep-it-not-me** [xbapps/xbvr#382]
I just started over with a new database - scraped the sites, and no VRB scenes have any tags on them. Other studios do.

**Comment by theRealKLH** [comment]
when was the last time you updated? This was fixed already in PR #371

**Comment by yep-it-not-me** [comment]
I am on 0.3.0-beta.34

**Comment by theRealKLH** [comment]
but when was the last time you updated? this was fixed 2 weeks ago.

**Comment by yep-it-not-me** [comment]
I'm on windows and do not want to setup dev stuff here. I'll wait for the next binary. 
:) good to know it's fixed already.

**Comment by theRealKLH** [comment]
@yep-it-not-me .. You can close this.

Duplicate of  issue #372 / fixed by #371

**Comment by yep-it-not-me** [comment]
@theRealKLH I'd prefer to leave it open until there's a new build I can test, if possible.

**Comment by yep-it-not-me** [comment]
I managed to build latest master locally and test, it works there. Closing.
