### ISSUE TITLE
Cardboard Mode Not Working

### ISSUE THREAD

**Issue by overloadedStasher** [xbapps/xbvr#383]
Hi,

I just started to use the app in Docker.
When I try to play a video on my iPhone (iOS 14.2) in 'normal' or cardboard mode, I cannot go in fullscreen.
Here's a few picture to document the problem.
It plays fine on my Mac, I can put it in fullscreen.

[Gallery](https://postimg.cc/gallery/by834FL)

**Comment by cld9x** [comment]
Web player was added with desktop in mind - if you want to play videos on iOS, please consider using dedicated app (e.g DeoVR, Mobile VR Station, etc)
