### ISSUE TITLE
correct Wankzvr MilfVR and TranzVR Filenames

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#386]
Correct filename for wankzvr MilfVR and TranzVR 

**wankzvr-wrong-house-right-hole-180_180x180_3dh_LR.mp4**

for all formats

needs fixing
remove scene ID and device format
![wvr](https://user-images.githubusercontent.com/16240121/99546578-8f616200-29dc-11eb-84ad-8af5093c6d7f.jpg)

Similarly for MVR and TVR

milfvr-<>-180_180x180_3dh_LR.mp4
tranzvr-<>-180_180x180_3dh_LR.mp4

**Comment by theRealKLH** [comment]
do you know all the naming for different formats? Is it just the 3? or is the like 4k,5k, etc?
