### ISSUE TITLE
Add release months for 2021

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#397]
![2021 01](https://user-images.githubusercontent.com/16240121/103442872-d3a07d00-4c7f-11eb-8720-6a57d5f4096e.jpg)

**Comment by theRealKLH** [comment]
I have it on mine...

![image](https://user-images.githubusercontent.com/65736720/103444193-3e2bcb80-4c34-11eb-9811-86f377cc486d.png)
