### ISSUE TITLE
Feature Request: Filter videos with multiple files

### ISSUE THREAD

**Issue by skinnerback** [xbapps/xbvr#400]
Making a feature request to add a filter to show videos with multiple files.  I find occasionally that I have a duplicate video or multiple versions of the same (Oculus 4k vs Oculus 5k, etc.)  A filter would make it easier to identify and remove the extra file vs having to scroll through the entire library looking for the multiple file marker on the card.

**Comment by Deflated-Criossant** [comment]
Use Search Everything
https://www.voidtools.com/

It will be a lot faster than XBVR

**Comment by skinnerback** [comment]
How would Search Everything help identifying duplicates when they have different file names, different hashes and are technically not the same because they have different specs?  By matching the video to the scenes in XBVR, its already identified as duplicate, but there is no easy way to filter to those or identify the duplicates in a large collection.

**Comment by andreaaraya01** [comment]
Is there a way to filter videos with more than 1 file?, I mean the light blue square at the bottom right of scene with the number of files linked to scene. I didn´t find a useful option in "sort by" menu. (I really would like to cooperate and add the feature by myself but I dont know how to program in the language of the project)

**Comment by theRealKLH** [comment]
@andreaaraya01 Not yelling at ya, but if you clicked on the above "closed" PR #1063 it would have led you to --> use the "attributes" box. "multiple video files"/"multiple script files".. it's in there (GRIN)
