### ISSUE TITLE
SinsVR unscrapeable

### ISSUE THREAD

**Issue by thisghguy** [xbapps/xbvr#405]
Seems the SinsVR site is permanently down. Any way to still match scenes? Scrape from another source (SLR)?

**Comment by theRealKLH** [comment]
SinsVR has totally redesigned their entire site (still seems to be changing). I am attempting to finish a PR. However, the "new" site currently only lists 48 VR videos. Some scenes also appear to have been "re-released" having dates newer than the original. They also seem to be doing some type of partnership with BadoinkVR network/RealJam/VRP Films, so vids are being "cross posted" from those sites.
