### ISSUE TITLE
Manual entry?

### ISSUE THREAD

**Issue by jwvanderbeck** [xbapps/xbvr#442]
I have a scene I downloaded from SLR that I can't seem to get scraped anywhere in the default scrapers, nor by pointing it directly to the scene URL.

Is there some way I can just manually enter this scene so that I can actually watch it?

**Comment by theRealKLH** [comment]
have you tried to manually match it from the files screen?

**Comment by jwvanderbeck** [comment]
Match it to what? There is nothing to match it to because the proper scene can't be scraped through any scrapers that I can find.

**Comment by theRealKLH** [comment]
Is it a scene that should be scrapable? what studio? unless you want to give us the name...

**Comment by jwvanderbeck** [comment]
Hence the desire to be able to manually make an entry without scraping :)

**Comment by theRealKLH** [comment]
currently you'd have to "false match" with an existing scraped scene and edit all the scene data manually.

**Comment by str0keR** [comment]
+1 being able to manually create a scene. I have, for example, seens from SinsVR that are no longer shown on their site so unable to be scraped. I'd like to be able to at least manually match the scene; provide some tags, scene name, cover image etc so I can watch the scene in DeoVR

**Comment by Noob34567** [comment]
How is the progress on this? Create manual entries would be awesome and a good way to handle scrappers that don't work.

**Comment by theRealKLH** [comment]
@jwvanderbeck cleaning "dead" issues. This should be resolved.
