### ISSUE TITLE
Scrapping issues - NaughtyAmerica

### ISSUE THREAD

**Issue by NFyr2nKsS9F6CH** [xbapps/xbvr#443]
I've tried every version between 0.3.5-0.3.8 and when initiating a new scrap for NaughtyAmerica, XBVR crashes. The UI states it is scrapping, but the actual XBVR.exe process is terminated. No issues scrapping any other sites that I scrape data for, only NaughtyAmerica seems to be the one causing this instant crash.

**Comment by theRealKLH** [comment]
Is this a "brand new" (just starting out) NaughtyAmerica scrape? (should be fixed by #441).  or updating (only need recent scenes)?

**Comment by NFyr2nKsS9F6CH** [comment]
Correct, happens on a "brand new" scrape. Good to know the fix is in the works, appreciate the work you all put into this project!

**Comment by cld9x** [comment]
Fixed in 0.3.9
