### ISSUE TITLE
DeoVR doesn't play "unmatched" files

### ISSUE THREAD

**Issue by mbalax11** [xbapps/xbvr#473]
Hi and thank you for making this awesome software.

I've had a problem for a while where no files in the "Unmatched" list in DeoVR start playing. I'm choosing the video but nothing happens. I use Oculus Quest 2.

I understand it's challenging to debug with so little information. I'd love to give you a debug log or something from DeoVR but I don't know how to extract it :sweat_smile: 

Any hints on how to proceed to figure out what's wrong?

**Comment by theRealKLH** [comment]
PR #470 was already submitted to fix this.
