### ISSUE TITLE
Running Scraper crashes XBVR

### ISSUE THREAD

**Issue by Deflated-Criossant** [xbapps/xbvr#496]
tried with v0.3.10 and 0.3.9

![Screenshot_131](https://user-images.githubusercontent.com/16240121/116422971-e1e15d00-a85d-11eb-9b79-48a797b47d9c.jpg)

last successful scrape : 2 days ago

I cleared %AppData\Roaming\xbvr\cache\scrape_cache
no change

**Comment by lockedmouse** [comment]
Looks like one of the scrapers is broken, can you please check which one it is? Click on ⋮ and then "Scrape this site" for each scraper until XBVR crashes.

I can confirm that it doesn't crash with 18VR, BadoinkVR or CzechVR.

**Comment by CelticShady** [comment]
RealjamVR is the broken scraper

**Comment by Deflated-Criossant** [comment]
thanks everyone for the quick fix

For now,I have turned off RJAM and it works fine

this is the best app to know site updates across

until next release

**Comment by Deflated-Criossant** [comment]
VRBangers scraper is broken
crashes XBVR
as mentioned in discord @cld9x

**Comment by WilsonBradley** [comment]
Same issue. Using latest 3.11
Crashing right as cursor goes over icon in taskbar. Which config file to rename / edit  scrapers , or which file to delete to get back to default? Will avoid the broken scrapers above.
