### ISSUE TITLE
NaughtyAmericaVR scraper causing crash

### ISSUE THREAD

**Issue by harrybaals72** [xbapps/xbvr#500]
"index out of range" error according to Docker logs

**Comment by harrybaals72** [comment]
Update: Appears there is no crash on the windows version of the app and according to the discord the docker image is not the latest due to build issues.

**Comment by theRealKLH** [comment]
@harrybaals72 

I'm up to date with NAVR (04/26/2021)- 599 scenes scraped. You sure it's not RealJamVR that's crashing (disable it & try again)? or update your installation. There was a new release .3.11 earlier today (yesterday-grin)

**Comment by harrybaals72** [comment]
> 
> 
> @harrybaals72
> 
> I'm up to date with NAVR (04/26/2021)- 599 scenes scraped. You sure it's not RealJamVR that's crashing (disable it & try again)? or update your installation. There was a new release .3.11 earlier today (yesterday-grin)

Both RealJamVR and NAVR cause crashes. The latest built on dockerhub was 15 days ago so it's just a matter of updating the image. Gonna try and build the docker image manually.
