### ISSUE TITLE
CzechVR scraper

### ISSUE THREAD

**Issue by T120S3** [xbapps/xbvr#504]
in 3.11 CzechVR and related sites have lost many matched files, and file name info seems to be populated with a file from realjamvr. Possibly a DB corruption? I tried to delete scraped scenes and force an update, but that is not working.

**Comment by theRealKLH** [comment]
yeah. this ticket and #503 ... you might have some kind of DB corruption going on. I just scraped Badoink & Czechvr w/clean DB and no issues. My running xbvr has no issues either. Both are scraping scenes, and generated filenames appear correct.

**Comment by T120S3** [comment]
Agreed, that's what seems to be happening. Thanks!
