### ISSUE TITLE
Unable to build search index or generate previews

### ISSUE THREAD

**Issue by dn8sh6HY** [xbapps/xbvr#505]
Hi,
I've installed XBVR in a Docker container through Portainer on OpenMediaVault 5. I'm able to scrape scenes, scan for files, and view them using DeoVR. However, I'm not able to build a search index (so I can't match scenes with files) and generating previews doesn't work either. 

If I try to test the generate preview settings, it works correctly and generates a preview. However, if I click on "Start generating previews" nothing happens and there is nothing in the logs.

If I trigger building a search index, I see the following output in the logs. Has anyone else had this issue? 

`
time="2021-05-06T16:56:59Z" level=info msg="Building search index..." task=scrape
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xfb9b3d]
routine 12139 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
github.com/blevesearch/bleve.(*indexImpl).Document(0x0, 0xc001e276f0, 0xa, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/blevesearch/bleve@v1.0.14/index_impl.go:327 +0x3d
github.com/xbapps/xbvr/pkg/tasks.(*Index).Exist(0xc00024eba0, 0xc001e276f0, 0xa, 0x0)
	/go/appsrc/pkg/tasks/search.go:39 +0x47
github.com/xbapps/xbvr/pkg/tasks.SearchIndex()
	/go/appsrc/pkg/tasks/search.go:91 +0x3e7
github.com/xbapps/xbvr/pkg/tasks.Scrape(0xc0016de01a, 0x8)
	/go/appsrc/pkg/tasks/content.go:190 +0x5db
created by github.com/xbapps/xbvr/pkg/api.TaskResource.scrape
	/go/appsrc/pkg/api/tasks.go:68 +0x8b
2021/05/06 16:56:59 ffprobe and avprobe not found in $PATH
time="2021-05-06T16:56:59Z" level=info msg="Migration did run successfully"
`

**Comment by lockedmouse** [comment]
Looking at the code, it appears that the call to [`bleve.NewUsing()`](https://github.com/xbapps/xbvr/blob/0.3.11/pkg/tasks/search.go#L29) returns an error. We only catch `ErrorIndexPathExists` and do not check for other errors, therefore `i.Bleve` is set to `nil`. When we later call [`i.Bleve.Document(id)`](https://github.com/blevesearch/bleve/blob/v1.0.14/index_impl.go#L326), it's no surprise that XBVR crashes.

I added some error logging in #510. If you can build the Docker image yourself, please test my branch, otherwise wait until it is merged into master and report back what error is logged with the next XBVR version.

**Comment by lockedmouse** [comment]
Also, in case the search index is corrupt, try deleting the contents of the `/root/.config/xbvr/search-v2` folder, then restart XBVR.

**Comment by dn8sh6HY** [comment]
Thanks for looking into this. I tried deleting the search-v2 folder and restarting but experienced the same issue.
I don't have any experience with building a Docker image myself so I think I'll wait until your branch is merged into the master, but I'll be sure to report back what error I find with the next version.

**Comment by dn8sh6HY** [comment]
After updating to 0.3.12, this is the error I seem to be getting when I try to search: 
`time="2021-05-23T13:58:46Z" level=error msg="no such device"`

No errors when I try to "Start generating previews" - nothing seems to happen at all.

I do get the following error periodically but I'm not sure what prompts it:
`2021/05/23 13:59:35 error transforming image https://vrpfilms.com/wp-content/uploads/fbrfg/apple-touch-icon.png#128x0: image: unknown format`

**Comment by theRealKLH** [comment]
@dn8sh6HY cleaning "dead" issues. if you are still having problems, resubmit.
