### ISSUE TITLE
XBVR Crash closing within seconds over hovering over taskbar icon 

### ISSUE THREAD

**Issue by WilsonBradley** [xbapps/xbvr#507]
XBVR Crash closing within seconds over hovering over taskbar icon 

From reading others, seems the scraping of certain locations are causing crashes.

HOW TO remove config file to load default.
What config file to rename to allow startup without scraping enabled?

**Comment by gollumsluvslave** [comment]
I had this issue as well - 0.3.16 was fine, but kept prompting for update (no way to hide?)
Moved to 0.3.17, systray app would crash. Completely cleaned out my old appdata (backed up) to get 0.3.17 to run (had to delete main.db)

Have now tried to recsrpare but get nothing from VRBangers. For now i'm going to have to rollback to 0.3.16 and my backed up DB as I don't seem to be able to restore any VRBangers scenes at all.

**Comment by gollumsluvslave** [comment]
Looking at commit dates on https://github.com/xbapps/xbvr/issues/597
looks like this was fixed just AFTER 0.3.17 was released, so I'm going to stick with 0.3.16, and wait for 0.3.18

**Comment by theRealKLH** [comment]
@WilsonBradley cleaning "dead" issues. going to say this was most likely resolved
