### ISSUE TITLE
View sessions not saved in 0.3.12

### ISSUE THREAD

**Issue by mbalax11** [xbapps/xbvr#525]
The scene's "Watch history" aren't updated with what I watch after I upgraded to 0.3.12 (from 0.3.11). Sorting for "Last view date" therefore doesn't work anymore. 

I use DeoVR with the "Enable remote control" setting on, and "Remote mode" enabled in XBVR.

I tried to disable the remote control both in DeoVR and XBVR. Then the watch history works again, but are less accurate.

**Comment by shushmo** [comment]
Same issue. Reverted versions and issue persists. Only workaround I've found is to turn off DeoVR remote control in web UI. Watch videos as normal on my headset, then switch remote control back on in the web UI. The "last viewed" videos are then updated based on what I viewed before re-enabling remote control. Messy fix but it works for now.

**Comment by theRealKLH** [comment]
@mbalax11 cleaning "dead" issues. Assuming this was resolved.
