### ISSUE TITLE
VRP Films updated, scraped file locations are now incorrect

### ISSUE THREAD

**Issue by T120S3** [xbapps/xbvr#526]
No images are loading for the scraped scenes, when I try the links manually you get "Oops! We couldn't find that page
Please navigate to another page" screen.

**Comment by nerfdaderp** [comment]
Can confirm this scraper is broken. No content shows under the any filter for the studio, whilst content I'm looking to tag can be found, (https://vrpfilms.com/m/single-tight-female in my case)

**Comment by theRealKLH** [comment]
scraper has been broken since May. Where you been? GRIN

**Comment by T120S3** [comment]
Thanks for the change to the SLR scraper! Everything matches and works.
