### ISSUE TITLE
Crash when generating heatmap

### ISSUE THREAD

**Issue by ghost** [xbapps/xbvr#544]
Hello,

Since the last version (0.3.13), XBVR keeps crashing at my place.

It's not systematic, but very often, when I do a recan (or when it does an automatic rescan), it tries to generate heatmaps and that's when it crashes.

![1](https://user-images.githubusercontent.com/60217162/121814204-12dfea80-cc70-11eb-9c5c-dad07fd4de8c.png)
![2](https://user-images.githubusercontent.com/60217162/121814211-1c695280-cc70-11eb-8fa0-6f0168469ccb.png)
![3](https://user-images.githubusercontent.com/60217162/121814219-212e0680-cc70-11eb-828d-d5f74b19012d.png)

But the generation of heatmaps is not done at each rescan.

Where can the problem come from?

Thank you in advance for the answer.

Thanks in advance for the answer.

[XBVR.zip](https://github.com/xbapps/xbvr/files/6644214/XBVR.zip)

**Comment by lockedmouse** [comment]
Looks like your funscript `A roll in the hay.funscript` has an error (e.g. XBVR is not allowed to read the file, or the file is invalid JSON).

#569 adds some more error handling so that instead of crashing, XBVR will just ignore your broken funscript file.
