### ISSUE TITLE
"File Data" export

### ISSUE THREAD

**Issue by Zalunda** [xbapps/xbvr#558]
Would it be possible to export the matches from the database?

It could be a new "File Data / Export" menu in the options, or it could simply be another table inside the scenes export. 

Something like this:

```
{
 "timestamp": "2021-08-14T15:48:37.9805409Z",
 "bundleVersion": "1",
 "scenes": [
  ...
  ],
  "files": [
  {
   "filename": "SLR_SLR_Originals_Sexual_Alchemy_Bali_Retreat_2900p_21099_MKX200_FB360.mp4",
   "scene_id": "slr-originals-21099",
  },
  ...
  ]
}
```

If I had that, I could do a simple application that read the json and rename all my files (which I know is not in the immediate plan of XBVR).

**Comment by theRealKLH** [comment]
@Zalunda cleaning "dead" issues. There are now multiple extract options available. Along with users creating/sharing their own "rename" scripts over on the Discord.
