### ISSUE TITLE
naughtyamericaVR

### ISSUE THREAD

**Issue by str0keR** [xbapps/xbvr#572]
Change scene URL to hit members.naughtyamerica.com rather than www.naughtyamerica.com

Currently when open a scene URL i have to manually edit the address bar to members.naughtyamerica.com and then log in and then download the scene (after first login then this works a bit more fluidly...) but would be nice to hit that members page first.

**Comment by theRealKLH** [comment]
this was previously brought up on the discord (by you?). Scraping is done on the public facing web site. How would you handle page changes / verification (does the page exist?) on the member side that we don't have access to?

**Comment by Deflated-Criossant** [comment]
> 
> Scrape the public pages then find/replace “[www.”](http://www.%E2%80%9D) with “members.” via some scraping post-processing? ?

use a url redirector
