### ISSUE TITLE
better auto-match

### ISSUE THREAD

**Issue by snickers2k** [xbapps/xbvr#581]
would be great to have some sort of a adjustable auto-match.
like two values; one for the score itself (like 300) and a second for the distance to the next match. 
If both, the first match is like 300/400, and the second one is 20 or so .. it's 100% always the right one, in my experience. I even saw one with a score of 600 and the next one like 50 or so, and it wasn't auto-matched.

second request for better auto-matching is respecting the date in a title with a simple regex, as well as the studio in front of the title, which seems to not be the case. the right studio, with the right date, is again 100% the right scene.

thanks

**Comment by gnadenlos** [comment]
I agree, studio and date should be ranked much higher. Often the top match is for the wrong studio or wrong date and it should and/or the scene is not found at all even if enough info is included in the file name. Also consider using infos like studio from the parent folder.

**Comment by theRealKLH** [comment]
@snickers2k cleaning up "dead" issues. if still an issue, reopen with more information. 

Process being described is not "auto-match". Updates to "search" functionality (PR #760) makes "manual" matching system closer to what OP is looking for?

**Comment by snickers2k** [comment]
@theRealKLH the request was about auto-match, not about search .. but okayy ..
