### ISSUE TITLE
"Could not migrate: invalid response from VRBangers API: no scenes found" after upgrading to 0.3.17

### ISSUE THREAD

**Issue by r3Fuze** [xbapps/xbvr#597]
Upgrading from 0.3.16 to 0.3.17 I now get this error when starting the container. It then restarts over and over again with the same error.

Downgrading to 0.3.16 makes everything work again so it seems like a problem with one of the two VRBangers related commits in the latest release.

**Comment by vorrac-stash** [comment]
Yeah, I'm having this issue and it sucks, since in 0.3.16 it keeps crashing when scraping and 0.3.17 does not start :(
