### ISSUE TITLE
Docker release 0.3.17 can not find ffbinaries

### ISSUE THREAD

**Issue by razfag** [xbapps/xbvr#601]
`ffprobe and avprobe not found in $PATH`
in the logs, download link might be broken?

**Comment by razfag** [comment]
Care to elaborate? The container crashed after updating it how to I "fix" it?

**Comment by theRealKLH** [comment]
the message is just saying that ffprobe & ffmpeg are not "found in the PATH".

the container is crashing due to changes VRBangers made on their website just prior to 0.3.17 release. use previous version 0.3.16 until a new release of xbvr has been released.
