### ISSUE TITLE
Latest update cannot migrate

### ISSUE THREAD

**Issue by overloadedStasher** [xbapps/xbvr#602]
I'm using XBVR in a docker container, and the latest upgrade cannot migrate. Here's the logs : 

`2021/10/21 11:42:50 ffprobe and avprobe not found in $PATH`
`time="2021-10-21T11:42:51-04:00" level=fatal msg="Could not migrate: invalid response from VRBangers API: no scenes found"
`

Thank you

**Comment by snickers2k** [comment]
> This was fixed in #598 and will be included in the next release.

could you maybe please upload that one as a quick-fix? like 0.17.1 ? thanks

**Comment by alexnsfw** [comment]
@snickers2k This is out of my control, it's up to @cld9x.
