### ISSUE TITLE
VRbangers scraper

### ISSUE THREAD

**Issue by vileda12** [xbapps/xbvr#612]
not finding any titles.

**Comment by vileda12** [comment]
is this fixed? why not update top 10 vr porn site afterall.

**Comment by alexnsfw** [comment]
This was fixed in #598 and will be included in the next release.

**Comment by andreaaraya01** [comment]
I have version 0.3.17 and it does not found any title yet to vrbangers

**Comment by theRealKLH** [comment]
@andreaaraya01 0.3.17 is not the "next release".

**Comment by Deflated-Criossant** [comment]
VRBangers scraper does not find new releases after 8 Oct 2021
using xbvr v0.3.17
Can the cloudflare issue be resolved?
