### ISSUE TITLE
Scenes not auto matching - filenames list does not contain correct files

### ISSUE THREAD

**Issue by dan9qt** [xbapps/xbvr#613]
If I go to edit a scene and see the filesnames list there are only ever 2 or 3 file names - The same 2 incorrenct random filenames, plus another correct one if I have manually matched a file.

I presume the above issue is why I also never get any scenes to automatch.

Anyway I can fix this? I presume its some sort of database error.

**Comment by alexnsfw** [comment]
Seems like you may be running into the bug fixed by #596, which will make it into the next release.

**Comment by dan9qt** [comment]
If that is the case, will the update fix current scenes, or only the ones going forwards?

**Comment by alexnsfw** [comment]
It will only fix current scenes if you do a force update (`Options > Scrapers > 3 dots > Force update scenes` for all scrapers then run scrapers).

**Comment by theRealKLH** [comment]
@dan9qt cleaning "dead" issues
