### ISSUE TITLE
Edit scene -> filename -> Add Item does nothing if filenames_arr is null

### ISSUE THREAD

**Issue by SilentMonkee** [xbapps/xbvr#620]
This is on Windows, I have null value for SinsVR and Tonight'sGirlfriendVR for the filenames_arr column.  Add Item button does nothing.  If I add a dummy item, then Add Item works.

**Comment by theRealKLH** [comment]
if it's null, why not just manually match the scene from the Files tab? null value means it's not going to automatch anyway. 

how are you adding dummy item if "add item" button doesn't work?

**Comment by vt-idiot** [comment]
> how are you adding dummy item if "add item" button doesn't work?

I'd love to know this, as there are bugged R18 titles with no DVD ID, and thus no scene ID in XBVR, that can't be matched as a result. I've resorted to pulling some other title, usually non 3D/VR, and just copying the info to it. This makes JAV an even bigger pain in the ass than it already is.

**Comment by theRealKLH** [comment]
> > how are you adding dummy item if "add item" button doesn't work?
> 
> I'd love to know this, as there are bugged R18 titles with no DVD ID

not the same thing. Possibly resolved with last PR that was merged.

**Comment by SilentMonkee** [comment]
Sorry for the late reply.

I added the dummy item from DB Browser.  

I don't recall the exact scenario why I was trying to do this, perhaps I was trying to manually match a scene that I know I owned but never show up in the match for the file.

**Comment by theRealKLH** [comment]
so you want help on something that's not "working as expected" after you manually manipulated things on the backend? grin...

How bout undoing whatever you did and let's start from there.

**Comment by SilentMonkee** [comment]
> so you want help on something that's not "working as expected" after you manually manipulated things on the backend? grin...
> 
> How bout undoing whatever you did and let's start from there.

I don't need help, my workaround worked for me.  It was not "working as expected" BEFORE I manually manipulated.  

PS. I was just reporting what I saw.  Don't expect the issue to be addressed.  Totally understand folks time are valuable.
