### ISSUE TITLE
New feature: Search options within XBVR via DEOVR

### ISSUE THREAD

**Issue by beauty789** [xbapps/xbvr#623]
Is it possible to make the XBVR catalog accessed through DEOVR be searchable (by typing in a search bar) especially the "unmatched" category? 
Or is this something only DEOVR has to do?

Also is there someways to make .mkv or wmv video's audio play in deovr with xbvr? (Quest 2)

**Comment by Rakly3** [comment]
Hi, I suggest using Search Everything on your PC for searching files. In the settings enable the http webhost.

The mkv and wmv incompatibilities are related to Oculus, not just DeoVR.
Google: oculus quest mkv

You would need something to transcode for them to work, Plex, Skybox...
Or do it yourself with Handbrake.

**Comment by beauty789** [comment]
Hi do you have a suggestion for mac osx search everything?

**Comment by theRealKLH** [comment]
@beauty789 cleaning up "dead" issues. search is not possible via DeoVR interface. it's closed API.
