### ISSUE TITLE
DLNA from XBVR running in Docker on Synology not working

### ISSUE THREAD

**Issue by jwvanderbeck** [xbapps/xbvr#627]
Hey all,

Wondering if anyone can  help me figure this out.  Are there any logs I can look at that might help?

I have XBVR running in a docker container on a Synology disk station and DLNA just plain up doesn't appear to work with any player.  I CAN use XBVR perfectly through the special DeoVR connection so the network connection seems fine, but any DLNA clients like Sybox or Pigasus. or even the DLNA option in DeoVR, or simply VLC on Windows, none of those see the DLNA server.

**Comment by jwvanderbeck** [comment]
Wondering if this might be a port issue.  What port does the DLNA server run on? I might need to set that up to forward to the Docker container?

**Comment by theRealKLH** [comment]
DeoVR is NEVER gonna work with DLNA. For the others (they "should" work), are you running on "host" network or are you trying to do some fancy "bridging" or some such?

**Comment by jwvanderbeck** [comment]
I'm not any sort of docker or synology expert.  I just set it up best I could figure out based on the process I used from a guide to setup containers for my other media services.  This included "forwarding" the ports 9999 and 9998 to the container, which is why I am wondering if there are other ports I need to setup for DLNA.

![image](https://user-images.githubusercontent.com/161126/146642272-1fd19a0b-c702-42d6-be98-b63b80d951d1.png)

**Comment by theRealKLH** [comment]
ok on Synology.... Pretty sure you have to make sure Network = host to get DLNA working.
![image](https://user-images.githubusercontent.com/65736720/146649041-0b88195c-54b9-4c55-af71-d84beb30a340.png)

Recreate your container and make sure to check the box.

**Comment by theRealKLH** [comment]
OR... maybe adding the 1338 port will be enough

**Comment by jwvanderbeck** [comment]
Thank you!  The port 1338 sadly didn't work, but recreating the container and using that Host option seems to have worked.  I'm not sure if there are any security implications, but it works :)
