### ISSUE TITLE
VRHush scraper pagination issues

### ISSUE THREAD

**Issue by ateb1t** [xbapps/xbvr#638]
The pagination for the VRHush scraper seems to get tripped up because of the '...' elipsis between page 8 and 9. The log shows that the scraper jumps for page 8 to page 87. I was able to fix the scraper by changing the element query on this line:

https://github.com/xbapps/xbvr/blob/master/pkg/scrape/vrhush.go#L124

The solution was to key off of the rel attribute of the anchor tag with the following code:

`siteCollector.OnHTML("a[rel=next]", func(e *colly.HTMLElement) {`

Unfortunately this caused another issue. It looks like VRHush is using StackPath to rate limit access to the site. So even after modifying the element selector scraping stops at around page 6/7 and using curl to test shows the following message:

`			<h1>Access Denied</h1>
			<p> <strong>vrhush.com</strong> is using a security service for protection against online attacks. An action has triggered the service and blocked your request. </p>
			<p> Please try again in a few minutes. If the issue persist, please contact the site owner for further assistance. </p>`

Using a VPN to rotate IP addresses seems to reset the filter but even hacking in some sleep statements to the pagination logic didn't allow the scraper to get any farther. 

Is this a known problem?

**Comment by theRealKLH** [comment]
@ateb1t cleaning "dead" issues. This was resolved
