### ISSUE TITLE
Docker Update

### ISSUE THREAD

**Issue by petex67** [xbapps/xbvr#666]
Please update docker with 0.3.19

**Comment by razfag** [comment]
To help you out this image includes the nightly build
https://hub.docker.com/r/coolmintchocolate/xbvr

As releases seem arbitrary and this "hotfix" took months might as well.

**Comment by TorvaldUtne** [comment]
> To help you out this image includes the nightly build https://hub.docker.com/r/coolmintchocolate/xbvr
> 
> As releases seem arbitrary and this "hotfix" took months might as well.

It looks like it hasn't been updated in 2 months though.

**Comment by theRealKLH** [comment]
@petex67 Think this issue can be closed. See 0.3.23

**Comment by theRealKLH** [comment]
@petex67 cleaning "dead" issues
