### ISSUE TITLE
Rescan Process Performance

### ISSUE THREAD

**Issue by gh4ms** [xbapps/xbvr#691]
Hello,
I'm wondering if the process of adding new files could not be more efficient, esp. since I'm running the application on a NAS which doesn't have the greatest performance. 

So, when I add a new file, I go to Storage -> Rescan and then:
a) all existing folders are scanned -> here a possibilty would be great to only trigger the rescan for a specific folder (this is already an old open issue: #340 )

b) the "Update status of Scenes" process takes quite long -> somehow for this all of the existing scenes (in my case almost 20k) are processed -> is there a reason why this is necessary each time, or would it be possible to only process newly addes files / scenes? 

c) the "Tag Count" process takes very long -> would it be possible to disable the tag count feature and this processing in general? Or at least make it more efficient by only adding the tags from newly added files / scenes, instead of going through ALL scenes and completly count again from zero each time (which seems to be the process right now)

**Comment by theRealKLH** [comment]
a. I'm going to say current implementation of that button isn't for you to "add a file. rescan. add another file. rescan". The rescan operation currently runs automatically every 2 hours. That button would be so if you "add a volume. rescan. delete a volume. rescan. shitton of file renames. rescan" for example not for "onesies twosies". 
b. see a. the less you click that button....
c. have you looked at the code to see that it's not "efficient" the way it is?

**Comment by gh4ms** [comment]
Ok, but isn't it still a pretty common usecase that this button is clicked right after adding a new file, in order to add it to the library immediately and see that it is matched correctly? (not wanting to wait up to two hours for the automatic rescan)

c) either way, it's something that takes several minutes each time (at least on a slow device like mine) and doesn't add much value in my opinion. 
Therefore, just as a suggestion / feature request: Please add a possibilty to activate/deactivate this functionality.

**Comment by razfag** [comment]
The problem imho is the using a relational database backend and a use case which adds the relations back in, essentially re-inventing indexes. (not that this would be any faster)

For now we are stuck with that but if there ever a major refactor I'd suggest using a nosql backend instead of sqlite.

**Comment by toshski** [comment]
re c) As at version 0.3.24 Tag & Actor counting uses the database to total the counts rather than in code and I would expect it to be significantly faster now
