### ISSUE TITLE
Can't get JSON import to work

### ISSUE THREAD

**Issue by SorenSkovSkov** [xbapps/xbvr#699]
I have a manually scraped file containing the videos from NaughtyAmerica's "CREAM.xxx" subsite since it's not indexable publicly and I can import it without issue in XBVR, but no scenes are actually added.

Is there any documentation on how this file should be structured in order to import successfully? I've looked through the code, but can't seem to find anything that would indicate that this file shouldn't import:

https://gist.github.com/SorenSkovSkov/df4d67444df7029ed489b4a32472d5f0#file-xbvr-bundle-for-na-creamxxx-json

Note, I'm not importing from that URL but from a local server that is readable. Loading it is not the issue.

**Comment by aciddtripp** [comment]
Looks like the scene_id is not being set correctly, causing it to overwrite an existing scene entry with one of the imports and not adding the rest. Check your first few entries in scenes table and make sure your existing data hasn't been corrupted.
If you change your "scene_id" field to "_id" instead it should all import correctly.

**Comment by SorenSkovSkov** [comment]
Thanks a lot @aciddtripp! That was exactly what was wrong.
