### ISSUE TITLE
xbvr 03.23 Scrapper don't work

### ISSUE THREAD

**Issue by Noob34567** [xbapps/xbvr#700]
Mutliple Scrapper don't work in xbvr 0.323

I reset the Seach Cache already. 

* VRHush
* VRAllure
* StripzVR
   * Videos that are listed on SLR aren't available in the scrapper, i.e. all Video from [Mila Azul](https://www.sexlikereal.com/pornstars/mila-azul)   

Is there something I can do or which kind of information can I provide to help?

**Comment by Noob34567** [comment]
Thanks @axw for moving the issue, would it also solve the StripzVR issue?

**Comment by axw-pub** [comment]
I'm focusing selfishly on VRHush for now but I might put in more work once that's done.

**Comment by theRealKLH** [comment]
@Noob34567 cleaning up "dead" issues. We are on 0.3.31. These issues were fixed
