### ISSUE TITLE
DeoVR issues

### ISSUE THREAD

**Issue by apache202119** [xbapps/xbvr#702]
In the latest release (at least on docker/armhf) the osd heart button doesn't work. Also I can't get to work the tracking of watched videos.

**Comment by theRealKLH** [comment]
osd heart button = inside Deovr? I click it and it's asking me to log in. Looks to be a "SLR only" feature (unless you are saying it used to work?). 

for "watched" status tracking, disable "remote mode" on options screen....
![image](https://user-images.githubusercontent.com/65736720/155785534-d0aa5695-61f7-4442-b3f2-53da068a9d8f.png)

**Comment by apache202119** [comment]
I'll try deactivating the remote mode, thanks. Regarding the heart button, yes I mean the one shown in the on screen menu while playing a video. Dunno if that worked before as I didn't use the app for a while, so closing this issue :)
