### ISSUE TITLE
Web video player not working for some videos

### ISSUE THREAD

**Issue by apache202119** [xbapps/xbvr#709]
Some videos are not playable on web, throwing these errors on browser console:
```
WebGL: INVALID_VALUE: texImage2D: no video
```
```
[.WebGL-0x3c0a1b3800]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
```

They work fine on DeoVR

**Comment by vt-idiot** [comment]
I don't think anyone is going to be able to help you much without the browser and the MediaInfo from the file. If I had to guess, it sounds like they're HEVC videos and you're using Firefox? They're the only ones that I can get to give any WebGL errors in the console. Browsers don't play nice with HEVC in general, both Google and Mozilla made a big deal out of it. Your only option is Microsoft Edge + HEVC Extensions, on Windows 10/11

The extension [used to be free](https://www.microsoft.com/en-us/p/hevc-video-extension/9n4wgh0z6vhq) but you should still be able to install it [using this link](ms-windows-store://pdp/?ProductId=9n4wgh0z6vhq). If GitHub breaks that formatting, the link is `ms-windows-store://pdp/?ProductId=9n4wgh0z6vhq` or you can type this in a command prompt: `start ms-windows-store://pdp/?ProductId=9n4wgh0z6vhq`

That should take you directly to the Store page for them.

"Proper" Way of Doing It for $0.99: https://www.microsoft.com/en-US/p/hevc-video-extensions/9nmzlz57r3t7

**Comment by Enissay** [comment]
What about linux ?

**Comment by vt-idiot** [comment]
The only other browsers that natively support HEVC without a custom player are Safari on both iOS and macOS and Chrome/Samsung Browser on some Android devices with hardware support.

From a cursory search, it looks like it's technically _possible_ to build Chromium with support for more audio/video codecs.

[Chromium.org mentions GN flags, but you can't use them to add formats Chrome itself doesn't support](https://www.chromium.org/audio-video/)
[Instructions for building Chromium (on Windows ???) with HEVC support](https://github.com/henrypp/chromium/blob/master/hevc_support_new.md)
[Russian guy getting it working on Ubuntu, information may be outdated, but it **is** possible](https://lexxai.blogspot.com/2016/09/chromium-ubuntu-x265-hevc.html)

**Comment by theRealKLH** [comment]
@apache202119 cleaning up "dead" issues. This doesn't appear to be xbvr related.
