### ISSUE TITLE
Configure Re-Scan and Re-Scrap time

### ISSUE THREAD

**Issue by Noob34567** [xbapps/xbvr#710]
My assumption is that XBVR scans the files periodically and also scraps the files again.

If my assumption is correct, it would be nice to make that timer configurable with the option to disable it. I prefer to trigger the re-scan manually.

**Comment by toshski** [comment]
Currently testing something for this.

For the Re-scrape and Re-scan tasks you can 
- Config the current setting, i.e. every 2 hours, etc., to you preferred frequency
- You can also specify a processing window, e.g. 18:00-06:00 if you only want to run overnight or 09:00-17:00 for during the day, 0-23 for all day
- If you specify a process window, you can specify how many minutes after the hour to start the task
- Can disable the task, so you only run it manually

Hopefully, that has a reasonable amount of flexibility and will cover most peoples requirements
