### ISSUE TITLE
Add sort options to deovr view

### ISSUE THREAD

**Issue by goodtimes2** [xbapps/xbvr#713]
I do not see an option to sort from deovr, or really search for that matter. If possible it would be nice to have those options available. Additionally I tried to toggle from web, to player view after sorting and that did not work.

**Comment by beauty789** [comment]
Yes please implement this!

**Comment by theRealKLH** [comment]
not possible within Deovr. From web, do your sort and create a "saved search" (check use as Deo list). then inside Deovr you can select it

**Comment by goodtimes2** [comment]
This worked perfectly.

**Comment by goodtimes2** [comment]
https://github.com/xbapps/xbvr/pull/722
