### ISSUE TITLE
Feature request - Custom/additional cuepoints

### ISSUE THREAD

**Issue by Nezen117** [xbapps/xbvr#763]
Hi,

I appreciate that there's cuepoints already made with the drop downs. I'd also like to have the ability to type in our own cuepoints that aren't in the drop down lists through the web interface. The way I've been achieving what I want has been through 'scene_cuepoints' in the db and manually changing them. It would save a lot of time if we just had the ability to type out custom cuepoints.

Thank you.

**Comment by toshski** [comment]
I have submitted PR https://github.com/xbapps/xbvr/pull/782 to do this
