### ISSUE TITLE
DeoVR - Unsupported video format when scene matched

### ISSUE THREAD

**Issue by 4gnusd3i** [xbapps/xbvr#822]
**Problem**: Some files cannot be played when its matched to a scene. However if the scene is unmatched, it plays without issue
**Troubleshooting**: Tried different variations of filenames; with _180_LR_ etc and without. Tried resetting DeoVR cache.

**Comment by theRealKLH** [comment]
you give no details about the files.

**Comment by soloist573** [comment]
@theRealKLH I have hit a similar issue and believe I can provide some more details, not sure if it is the same issue exactly but it should be reproducible.

I don't remember which scraper it was exactly, though I know a couple of them have this problem. Basically if there is no release date on the scraped file, XBVR defaults it to 0001-01-01.

It seems DeoVR cannot parse this correctly with its "n days ago" thing in the info panel and just refuses to play it (it's a negative epoch value I think is why).

If you update the release data manually to be 1970-01-01 the video will play. I'm not sure what the best fix is on XBVR side, perhaps date can be left completely blank? Or at least default it to epoch date.
