### ISSUE TITLE
Add tag/actor search like the SLR website

### ISSUE THREAD

**Issue by nycedwardd** [xbapps/xbvr#902]
The SLR website has a bar on the side with selectable tags, and a search function where performers, studios and tags can be selected. It would be great if this could be added to xbvr as well.

**Comment by theRealKLH** [comment]
you already have that in Web interface (create a saved search)...
![image](https://user-images.githubusercontent.com/65736720/182867574-21db5d11-b215-4dbe-9c63-d455dac52257.png)
If you are talking about inside DeoVR.. that's not possible. SLR is using hidden internal APIs to do that.

**Comment by theRealKLH** [comment]
@nycedwardd cleaning up "dead" issues. if still an issue, reopen with more information.
