### ISSUE TITLE
Ability to configure port or change default port of 9999

### ISSUE THREAD

**Issue by wheresmytissue** [xbapps/xbvr#948]
The default port of 9999 appears hard coded in a number of [locations](https://github.com/xbapps/xbvr/search?q=9999).

Request: Ability to set the port when initializing docker container or update readme with instructions how to do this. 

thank you

**Comment by toshski** [comment]
The system will default to 9999 when you run it for the first time.  It then saves the port to use in the database.  Check in the "kv" table for a record with the key "config".  This has a json string and you should see port 9999 as one of the early entries.

If you are using Docker, you will need to change your port mappings for your particular environment.

**Comment by theRealKLH** [comment]
@wheresmytissue cleaning up "dead" issues. this issue resolved by following @toshski's advice. You need to pass your port mapping (host:container) in via docker settings.
