### ISSUE TITLE
XBVR almost a year out of date on DockerHub Registry

### ISSUE THREAD

**Issue by ilikemediumbutts** [xbapps/xbvr#951]
The version of XBVR listed as "latest" on Dockerhub is nearly a year out of date, so when you install it from the Dockerhub registry on Synology/etc. you end up stuck with a very old version.

[https://hub.docker.com/r/xbapps/xbvr](url)

Would it be possible for someone to get the Dockerhub/Registry entry for XBVR updated, or set it up so that it updates with each new version again? It's stuck on 3.17 or whatever was around last October. I know there are other ways of installing, but by far the easiest way of setting up XBVR on Synology/etc. is by just creating a container from the official DockerHub listing. Having a working and up-to-date dockerhub listing could help expand the userbase.

**Comment by theRealKLH** [comment]
XBVR is now only releasing on GitHub Registry GHCR.IO (see README). For Synology you can either update manually via terminal (ssh) or install Portainer (and add the GH registry) or use my image... search for iamklh/xbvr:latest

**Comment by theRealKLH** [comment]
@ilikemediumbutts cleaning up "dead" issues. if still an issue, reopen with more information.
