### ISSUE TITLE
FuckPassVR Scraper misses scenes

### ISSUE THREAD

**Issue by 3dnsfw** [xbapps/xbvr#976]
The FuckPassVR Scraper scrapes from `https://www.sexlikereal.com/studios/fuckpassvr` but that doesn't contain all scenes.

For example `https://www.fuckpassvr.com/video/kangaroo-style-in-melbourne`
(On TPDB: `https://metadataapi.net/scenes/fuckpassvr-kangaroo-style-in-melbourne`)
is not found

**Comment by gnadenlos** [comment]
A real FuckPassVR scraper would be great. SLR is a few releases behind, misses some scenes, has wrong dates (because of the delay) and the encodes on SLR are 30Mbps only, while the studio website offers 45Mbps encodes.

**Comment by gnadenlos** [comment]
Missing scenes on SLR and therefore in scraped data:

https://www.fuckpassvr.com/video/chrysanthemum-for-your-sword-in-osaka
https://www.fuckpassvr.com/video/flamenco-flame-in-barcelona
https://www.fuckpassvr.com/video/kangaroo-style-in-melbourne
https://www.fuckpassvr.com/video/midday-in-saint-petersburg
https://www.fuckpassvr.com/video/deep-tissue-massage-in-tabor
(+ latest two scenes)

**Comment by gnadenlos** [comment]
FuckPassVR intentionally keeps some scenes "exclusive" now. So it would be really good to get a "native" scraper, because the scenes missing on SLR raises all the time.

**Comment by teiffs** [comment]
can you supply example filenames for each of the different resolutions of a video?

**Comment by theRealKLH** [comment]
@gnadenlos please supply example filename for each resolution you can download.

**Comment by theRealKLH** [comment]
I gave it a try. FuckpassVR is currently not scrapable by xbvr in its current state because the pages are dynamically created by javascript. There is no data in the html.
